### ISSUE TITLE
No Linux on arm64 support

### ISSUE THREAD

**Issue by astatio** [realm/realm-kotlin#1010]
I've came across the unfortunate situation to try and run a jar I made on a Raspberry Pi only for it to fail with
`Caused by: java.lang.UnsatisfiedLinkError: /home/SCBot/.cache/io.realm.kotlin/5be26df68d0a52806a65434a218ae23faf9de4eb/librealmc.so: /home/SCBot/.cache/io.realm.kotlin/5be26df68d0a52806a65434a218ae23faf9de4eb/librealmc.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64 .so on a AARCH64 platform)`
The thing is: why is this not stated anywhere in the docs? The max I could find was a list of supported KMM environments https://www.mongodb.com/docs/realm/sdk/kotlin/install/kotlin-multiplatform/#supported-target-environments
And then: why does it support arm64 on MacOS but not Linux on the same architecture? I'm legitly curious

**Comment by cmelchior** [comment]
Hi @astatio 

The list at https://www.mongodb.com/docs/realm/sdk/kotlin/install/kotlin-multiplatform/#supported-target-environments is indeed the list of the targets we currently support.

Nothing technically prevents us from shipping support for Linux arm64, except that we need to have the proper CI setup to make sure that works. So far we haven't prioritized that, but there have been a few requests for it now, so it is some we will be reevaluating.

This is already being tracked here: https://github.com/realm/realm-kotlin/issues/617 so I will be folding this issue into that one.
