### ISSUE TITLE
UPDATE instruction had incorrect partition value for key "_partition" { expectedPartition: xxx, foundPartition: (ProtocolErrorCode=212)

### ISSUE THREAD

**Issue by CavalcanteLeo** [realm/realm-kotlin#1012]
Hi everyone, somehow my app has saved some wrong partition for some users, but we can't lose all those data with wrong partitions.

When the app tries to sync the data, it gets an error: 
```shell
UPDATE instruction had incorrect partition value for key "_partition" { expectedPartition: xxx, foundPartition: (ProtocolErrorCode=212)
````

But some partitions are correctly and already on server.

How can i update the partition on a local data and sync it to server?

**Comment by clementetb** [comment]
I am afraid you cannot just update the partition key. You would need to move the data manually from the wrong partitioned Realm to a Realm with the right partition key.

To do so, you will need to:

- create two different SyncConfigurations each with a partition key
- open a Realm instance on each configuration
- copy the data
