### ISSUE TITLE
java.lang.IllegalArgumentException: Only subclasses of RealmObject and EmbeddedRealmObject are allowed in the schema.

### ISSUE THREAD

**Issue by ASAKURA404** [realm/realm-kotlin#1023]
I use realm in KMM.

Realm Object is this.
```kotlin
class ItemEntity : RealmObject {
    var itemId: String = ""

}

class HabitEntity : RealmObject {
    var habitType: String = ""

}
```

Repository is this.
```kotlin
class ItemRepository {
    lateinit var configuration: RealmConfiguration

    fun initialize() {
        configuration =
            RealmConfiguration.create(
                schema = setOf(
                    ItemEntity::class,
                    HabitEntity::class
                )
            )
    }
}
```

When I start app in Android, app crashed.
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/48251111/192089132-93d039c0-ec15-4408-b65a-c27e31cb0dcb.png">

I think realm object is good, why I have a crash?
I found same probrem here.
[Mongo DB Realm \- Only subclasses of RealmObject and EmbeddedRealmObject are allowed in the schema \| SolveForum](https://solveforum.com/forums/threads/mongo-db-realm-only-subclasses-of-realmobject-and-embeddedrealmobject-are-allowed-in-the-schema.1463424/)

Is this bug? Or my mistake?

kotlin: 1.6.10
realm: 1.1.0

**Comment by rorbech** [comment]
Hi @ASAKURA404. Are you sure that you apply the plugin as described in the installation section (https://github.com/realm/realm-kotlin#installation)?

**Comment by ASAKURA404** [comment]
My apologies, I made an elementary mistake.
I thought I had installed the plugin, but I did not.
Thank you very much.

**Comment by zitzat9** [comment]
can you show me how to fix this bug?

**Comment by rorbech** [comment]
@zitzat9 You just need to apply the Realm Kotlin plugin in your `plugins`-section of your Gradle setup. 
```
plugins {
    ...
    id("io.realm.kotlin") version "1.5.1"
}
```
Note that the setup and where to specify the version can vary depending on whether it is an Android-only or Kotlin Multi platform project. You can see more detailed examples in the links referenced from https://github.com/realm/realm-kotlin#installation

**Comment by rorbech** [comment]
@zitzat9 Are you sure that you have applied the plugin for all project modules that contain you model classes? 
Maybe try to dump the compile time dependencies to see if the our compiler plugin are in fact on the compile time class path with something like (might have to adjust a bit to fit your project/flavor setup) 
```
 ./gradlew :dependencies --configuration=debugCompileClasspath
```
and dump the actual stack trace of the error so that we have a chance to see where the error originates from.
