### ISSUE TITLE
Missing branches using Jacoco

### ISSUE THREAD

**Issue by joaodevsantos** [realm/realm-kotlin#1026]
I'm developing some unit tests for my project realm and embedded realm objects and I'm facing the following issues on the resulting JaCoCo report:

- All classes claim to have a missing branch on the following element. I have tried different approaches but nothing solves this.

![Screenshot 2022-09-26 at 17 09 19](https://user-images.githubusercontent.com/43722840/192326830-9d622963-d303-4d42-a615-20f3ad1ddac3.png)

- On setters and getters it claims that exists a missing branch but I have tried all different initialization combinations (i.e., empty constructor and constructor with different values)

![Screenshot 2022-09-26 at 17 10 28](https://user-images.githubusercontent.com/43722840/192326992-f4ed36ac-5a45-475d-9ee4-d220ab5a6697.png)
![Screenshot 2022-09-26 at 17 10 49](https://user-images.githubusercontent.com/43722840/192327067-fb217b2a-ff43-4c95-8036-b0902cbf5f82.png)

I would like some help on this to increase my code coverage.

**Comment by cmelchior** [comment]
Most likely you need a managed RealmObject for those branches.

We change the getters and setters under the hood to either go into the database or read from the in-memory object. It is described here: https://github.com/realm/realm-kotlin/blob/master/packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/AccessorModifierIrGeneration.kt#L544

**Comment by cmelchior** [comment]
If you can post a unit test, it is probably easier to see exactly which branches you might be missing?

**Comment by joaodevsantos** [comment]
> If you can post a unit test, it is probably easier to see exactly which branches you might be missing?

I was only trying to unit test the objects isolated. I let here a simple example testing the email field of an User realm object.

`
@Test
    fun `test email empty`() {
        val objectInTest = CacheUser()

        objectInTest.run {
            objectInTest.email = ""
        }
    }

    @Test
    fun `test email not empty`() {
        val expectedEmail = "test@test.test"
        
        val objectInTest = CacheUser().apply { 
            email = expectedEmail
        }

        objectInTest.run {
            objectInTest.email = expectedEmail
        }
    }
`

**Comment by cmelchior** [comment]
Yes, those unit tests will miss our "managed" branches. If you do something like this, it should cover both:

```
   @Test
    fun testEmailEmpty() = runBlocking {
        val realm: Realm = getRealm()
        val objectInTest = CacheUser()
        val managedObj: CacheUser = realm.write {
           copyToRealm(objectInTest)
        }
        assertEquals(objectInTest.email, managedObj.email)
    }
```

**Comment by joaodevsantos** [comment]
> Yes, those unit tests will miss our "managed" branches. If you do something like this, it should cover both:
> 
> ```
>    @Test
>     fun testEmailEmpty() = runBlocking {
>         val realm: Realm = getRealm()
>         val objectInTest = CacheUser()
>         val managedObj: CacheUser = realm.write {
>            copyToRealm(objectInTest)
>         }
>         assertEquals(objectInTest.email, managedObj.email)
>     }
> ```

I have tried to implement that approach but I ran into the following problem:

```
Caused by: java.lang.NullPointerException: RELEASE must not be null
```

With a quick search I noticed that this problem was already noticed by you and you have an [open issue with Jetbrains](https://github.com/realm/realm-kotlin/issues/917). But my solution for now is to ignore the realm and embedded realm objects from JaCoCo reports and testing them through instrumented tests.

Anyway, thanks for your availability!
