### ISSUE TITLE
Multiplatform: Realm crashes when accessed from iOS

### ISSUE THREAD

**Issue by DarkSatyr** [realm/realm-kotlin#1053]
Method:
```
fun getPortfolios(): Portfolios {
        return realm.query(PortfolioData::class).find()
            .map {
                Portfolio(it.date, it.stringValue)
            }
    }
```

crashes on iOS (on map line)

<img width="1861" alt="Screen Shot 2022-10-05 at 5 54 26 PM" src="https://user-images.githubusercontent.com/20116857/194092538-b541058d-a177-4e7f-8e59-d5629afe4edc.png">

**Comment by cmelchior** [comment]
That code doesn't look like it should compile 🤔  `realm.query(PortofolioData::class).find()` will return a `RealmResults<PortfolioData>`...you cannot map that into a `Portfolios` ?

**Comment by DarkSatyr** [comment]
@cmelchior it compiles, because RealmResults inherits List, but if I add realm.query(PortofolioData::class).find().toList it gonna crash also

**Comment by cmelchior** [comment]
Do you have the full stacktrace?

**Comment by DarkSatyr** [comment]
@cmelchior sure
full https://pastebin.com/GD7XRYK8
<img width="1859" alt="Screen Shot 2022-10-05 at 8 41 09 PM" src="https://user-images.githubusercontent.com/20116857/194126192-4f603c17-42a1-47fd-b50d-303c3169de36.png">

**Comment by cmelchior** [comment]
Hmm, interesting. That is very surprising it crashes as we should have plenty of unit tests for that particular piece of code.
Is it something you can reproduce in as sample project we can debug?

**Comment by DarkSatyr** [comment]
@cmelchior here you go, app crashes on iOS
Mac OS Monterey 12.6, macbook air M1
https://filetransfer.io/data-package/4mQMLCvy#link

**Comment by cmelchior** [comment]
The problem is due to the memory model on Kotlin Native:

![image](https://user-images.githubusercontent.com/406066/194696346-07cf484c-f13d-4d21-b41a-9a9a1fb82d0e.png)

It is a bit unclear why you are hitting this as our API's should be compatible with both versions of the memory model (which could point to a bug on our side).

But moving to the new memory model fixes the problem. You can do that by adding this to the top-level `gradle.properties` file:

```
# Enable new Kotlin Native memory model
# See https://kotlinlang.org/docs/native-memory-manager.html
kotlin.native.binary.memoryModel=experimental
kotlin.native.binary.freezing=disabled
```

This is also the default mode in Kotlin 1.7.20. Realm doesn't support that just yet, but will do shortly: https://github.com/realm/realm-kotlin/issues/1024

**Comment by DarkSatyr** [comment]
@cmelchior thanks for pointing out
so, it works in a project from iOS side, but if I try to build it like xcframework and then use it in another project I'm still getting a crash, here is the stack trace:
https://pastebin.com/FZfy3sec

and final version of the test example:
https://filetransfer.io/data-package/5XaDTxM4#link

**Comment by clementetb** [comment]
> and final version of the test example:
https://filetransfer.io/data-package/5XaDTxM4#link

This project uses Ktor 2.1.1 (new memory model) + Realm 1.2.0 (old memory model), they must use the same model.

Try with Realm version 1.4.0.

**Comment by DarkSatyr** [comment]
@clementetb it works, thanks!
