### ISSUE TITLE
Realm.asFlow() is not being triggered on Sync changes.

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#1070]
Looks like our `Realm.asFlow()` isn't being triggered when there is a remote change, whereas queries are being triggered correctly:

```
realm.asFlow().collect {
  // Is not being triggered when changes are coming from another device
  println("$it -> ${it.realm.version()}")
}
realm.query<FlexParentObject>().asFlow().collect {
  // Works if changes are coming from another device
  println("$it -> ${it.list.size}")
}
```

This test reproduces the issue: https://github.com/realm/realm-kotlin/pull/1071/files#diff-65ad5644786458a5a2bc5d99f679e8533faf91be5c5ec9aedf806cba336acaefR214

**Comment by rorbech** [comment]
Seems to be that we are only initializing the `nofitier`'s internal `LiveRealm` when we are actually listening for something other that top level realm update. So the `realm_add_realm_changed_callback` is not registered before listening for something else. An immediate workaround until a fix is ready would be to just trigger some notification, ex.
```
async { realm.query<X>.asFlow().first {} }
```
