### ISSUE TITLE
Write transactions increase Realm version number on each call

### ISSUE THREAD

**Issue by Nek-12** [realm/realm-kotlin#1081]
Hi! This is more of a question of understanding how to keep realm versions low

I'm using the following code to write to the database:

```kotlin
override suspend fun save(e: Entry): Entry = Entry(db.write { upsert(e) })

// equal to, using inline functions:

suspend fun save(e: Entry): Entry = realm.write {
     val rid: RealmUUID = e.id
     
     val update: EntryEntity.() -> Unit = {
          property = e.property
     }
     val entity = query<EntryEntity>("id == $0", rid).first().find() ?: EntryEntity().apply { id = rid }
     copyToRealm(entity.apply(update), UpdatePolicy.ERROR)
}.mapToEntryDataClass() // maps the object to a domain model immediately outside of the db.write {} block
```
The save() function is invoked on a background thread (Dispatchers.IO or Dispatchers.Default)

I'm using a global singleton instance provided with Koin to my app

```kotlin
single(createdAtStart = true) { provideDatabase() } // <-- provideDatabase() creates and opens a Realm instance
```
And a few of the DAO objects, singletons too, accessed on random dispatchers.

But while queries run on Dispatchers.IO using this code:
```kotlin
internal suspend inline fun <T : BaseRealmObject> RealmQuery<T>.findSuspend(
    context: CoroutineContext = Dispatchers.IO
) = withContext(context) { find() }

// result is immediately mapped to domain object
```
all run fine, each write operation produces the following Logcat output:
```
     D  Updating Realm version: VersionId(version=50) -> VersionId(version=51)
     D  Closing unreferenced version: 49
     D  Updating Realm version: VersionId(version=51) -> VersionId(version=51)
     D  Updating Realm version: VersionId(version=51) -> VersionId(version=52)
     // each write produces 2 version increments
     D  Updating Realm version: VersionId(version=52) -> VersionId(version=52)
     D  Updating Realm version: VersionId(version=52) -> VersionId(version=53)
     
     D  Updating Realm version: VersionId(version=53) -> VersionId(version=53)
     D  Updating Realm version: VersionId(version=53) -> VersionId(version=54)
     
     D  Updating Realm version: VersionId(version=54) -> VersionId(version=54)
     D  Updating Realm version: VersionId(version=54) -> VersionId(version=55)
     
     D  Updating Realm version: VersionId(version=55) -> VersionId(version=55)
     D  Updating Realm version: VersionId(version=55) -> VersionId(version=56)
     
     D  Updating Realm version: VersionId(version=56) -> VersionId(version=56)
     
     // this is output immediately before crash
     D  Closing unreferenced version: 55
     D  Closing unreferenced version: 54
     D  Closing unreferenced version: 55
     D  Closing unreferenced version: 53
     D  Closing unreferenced version: 54
     D  Closing unreferenced version: 52
     D  Closing unreferenced version: 53
     D  Closing unreferenced version: 51
     D  Closing unreferenced version: 52
     D  Closing unreferenced version: 51
     D  Updating Realm version: VersionId(version=56) -> VersionId(version=57)
     D  Updating Realm version: VersionId(version=57) -> VersionId(version=57)
     E  Error:  java.lang.IllegalStateException: Cannot begin the write transaction: RealmCoreException([5]: Number of active versions (9) in the Realm exceeded the limit of 8)
```

Could you help me find out where do I leak Entity objects in my code? I don't really understand where could they be stored as I never return an EntryEntity from my dao, everything is mapped right after it's returned from the write block or after executing find()

I tried for a long time to find any public method for freezing an object /manually making it unmanaged, couldn't find any.

Realm version: 1.4.0
Platform: Android
Kotlin 1.7.20

My upsert function, which is probably the culprit:

```
internal inline fun <reified T : RealmObject> MutableRealm.upsert(
    id: Uuid,
    crossinline create: (RealmUUID) -> T, // verified this is not evaluated unnecessarily
    crossinline update: T.() -> Unit,
): T {
    val rid = id.toRealmUUID()
    val entity = query<T>("id == $0", rid).first().find() ?: create(rid)
    return copyToRealm(entity.apply(update), UpdatePolicy.ERROR)
}
```

**Comment by clementetb** [comment]
What are you doing with the entity after invoking `save`? Are you storing the data in a memory structure?

**Comment by ganfra** [comment]
Can this be related to https://github.com/realm/realm-kotlin/issues/1007 ?

**Comment by Nek-12** [comment]
Yes, I've seen #1007 and this may very well be related. 
After calling save, I'm mapping the entity to a domain-level data class (directly invoking the constructor and mapping non primitive types), and passing it back to the repository. The repository either returns it where it is mapped again for display, or discards it

**Comment by clementetb** [comment]
@Nek-12 does the workaround from #1007 works for you?
>Closing/Opening the realm instance between each transaction keep the number of version to 1, but the doc clearly indicates to keep a global singleton instance.

**Comment by clementetb** [comment]
Antoher question, how come that you have a limit of 9 realm instances?

**Comment by ganfra** [comment]
On my side I just used ` .maxNumberOfActiveVersions()` which is by default 8

**Comment by Nek-12** [comment]
@clementetb yes, the workaround works, but I do not think this is an acceptable solution.

Yes, I'm using the maxNumberOfActiveVersions() as ganfra does, too.

Could it just be due to the simple fact that garbage-collected objects are not guaranteed to be removed from the heap immediately? I'll try running garbage collector after a write statement.

**Comment by clementetb** [comment]
Yes, the "workaround" is not acceptable, I wanted to be sure that we were talking about the same issue. 

The issue comes because the Realm instances cannot be closed until the objects instances are not garbage collected. Manually triggering the GC would be a workaround to the issue. 

At some point, we will implement a solution to be able to release such resources manually, see https://github.com/realm/realm-kotlin/issues/709

**Comment by ganfra** [comment]
We can't force a GC, and thats a bad practice too. So we don't have a proper solution now?

**Comment by Nek-12** [comment]
No, I don't think the solution proposed in #709 is acceptable too, @clementetb. 
Imagine having to call a manual release code every single time on every single object each time we operate on it, at the right time? That would make Realm as a library very hard to work with, because one slipped live version of an object, and you'll have either a "realm file size leak" (grows infinitely), or, if you try to take countermeasures against it, a runtime crash at unpredictable times (e.g. after 9 writes for a specific method)

This is, it turns out, just as I suspected, a fundamental issue in how Realm works with the GC.
Entities should be released automatically and as soon as their reference count reaches zero (not via a weak pointer / reference, but rather via a database-provided memory-management construct. 

A suggested approach would be to remodel how Realm works with references to only allow managed (live) objects to exist inside a transaction (mutable realm scope). This would allow the database to keep track of any live objects and decrease the live object count as soon as the user is done mutating the database data. 

This approach would look like having to use copyFromRealm(object), where the MutableRealm would keep track of it and make the object unmanaged as soon as the write {} block is left. A terrible and backward-incompatible solution, but the only one I can think of.

**Comment by ganfra** [comment]
Yeah thats not manageable. 
We can't switch to another library on our side, but this makes the realm-kotlin not usable for now.
Realm-java doesn't have this issue as long as you don't use frozen objects I guess.

**Comment by ganfra** [comment]
@clementetb @cmelchior are you going to do something on your side soon or are we stuck with that?

**Comment by ganfra** [comment]
Thanks @cmelchior for the long answer.

On our side, having the 1. and 3. would cover most of our cases, but 2. and 4. could also be useful in some scenarios.

In our project, we often got the big file-size growth report in #1007, as we have lots of transactions and active flows in parallel. Hopefully [this](https://github.com/realm/realm-core/pull/5440) will fix the issue waiting to have more control over the memory management.

**Comment by Nek-12** [comment]
If I had to choose the thing with most priority, I'd choose 2.2 : projections. 

I understand the promise of lazy loading, however, as nice as that may sound, right now mobile architecture has evolved significantly, so that passing database objects to the ui layer is no longer acceptable. This is especially true for Compose with its `@Stable` type api and in general with Clean Architecture. In most modern existing apps right now, any data emitted from the database will be mapped to another object at least once.

Using solutions like 3 won't solve this specific problem, and solutions like 4 won't be necessary as I believe something like what you described is a very unlikely edge case, according to my arguments above.

I think that the API outlined in (1) should still be implemented for greater flexibility of working with data before it's passed up to the UI / business logic.

We could define a "standard" projection data class which would contain all fields of an entity, and the user can define their custom projections later. This would enable essentially the same API as (1) but with a nicer surface and that would abstract away the implementation of the database

To be honest, using realm, it was very, very painful to learn all the intricacies of how it works under the hood to make it work, for someone coming from SQL the learning curve is huge as it is. So I'd avoid exposing even more implementation details to the general beginner-user.

**Comment by ganfra** [comment]
On our side, we don't have strong opinions about the API as long as it allows us to easily map to domain/ui layer and release memory.
Usually we don't return the data from the transaction, thats why 1. was an easy solution for transaction. 
The projection API 2.2 would be great indeed, but might be longer to develop than solution 3, which would at least offer the ability to release frozen objects after they are manually mapped.

@cmelchior can you at least ping us when https://github.com/realm/realm-core/pull/5440 land in realm-kotlin?

**Comment by cmelchior** [comment]
@ganfra Yes, we will update you.
