### ISSUE TITLE
KMM install docs are wrong

### ISSUE THREAD

**Issue by J-Swift** [realm/realm-kotlin#1087]
(I didnt see a way to edit them on the page)

On the KMM install page (https://www.mongodb.com/docs/realm/sdk/kotlin/install/kotlin-multiplatform/) it says if you want to reference Realm in the android project you need to add
```
dependencies {
   compileOnly("io.realm.kotlin:library:1.2.0")
}
```
but it should be
```
dependencies {
   compileOnly("io.realm.kotlin:library-base:1.2.0")
}
```

Burned a couple hours trying to figure out why my stuff wasn't compiling : (

**Comment by cmelchior** [comment]
Hi @J-Swift Yes, sorry about that. We will get that fixed quickly.
