### ISSUE TITLE
RealmObject `equals` are probably not correct

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#1097]
When reading objects from Realm, we use their default `equals` implementation, which compares by memory reference. This means that the following behavior can be observed:

```
realm.writeBlocking {
            val result = copyToRealm(sample)
            val obj1 = result.nullableObject
            val obj2 = result.nullableObject
            assertNotEquals(obj1, obj2) // Managed objects use default `equals`, i.e. compare mem ref. 
}
```

This is probably not what you would expect, and we should consider if managed objects should have their own equals implementation that compare <ClassKey,ObjectKey,Version> instead. It would probably have to be implemented in the Compiler Plugin so we can avoid generating it if users have their own equals method.

We should also take into account `RealmAny` instances containing objects.

**Comment by tarasmorskyi-mediamonks** [comment]
Any update on this? Is currently the only option is to compare value by value aka deepEquals?

**Comment by tarasmorskyi-mediamonks** [comment]
@cmelchior tagging you as reporter

**Comment by cmelchior** [comment]
It appears this issue fell through the cracks and should be fixed soon.
