### ISSUE TITLE
Proguard rules update

### ISSUE THREAD

**Issue by tarasmorskyi-mediamonks** [realm/realm-kotlin#1107]
add missing rules

-keep class io.realm.kotlin.types.EmbeddedRealmObject
-keep class * implements io.realm.kotlin.types.EmbeddedRealmObject { *; }

**Comment by nhachicha** [comment]
Thanks @tarasmorskyi-mediamonks 
@rorbech I think we missed to add proguard rules in https://github.com/realm/realm-kotlin/pull/797/files

**Comment by nhachicha** [comment]
fixed via https://github.com/realm/realm-kotlin/pull/1109
