### ISSUE TITLE
Duplicate UUID generated with RealmUUID.random()

### ISSUE THREAD

**Issue by mohit-sharma-87** [realm/realm-kotlin#1123]
Hello, 

I have noticed that UUID random function is not returning unique IDs and the issue gets fixed only when the app is reinstalled. 

My sample implementation : 

![Code snippets](https://user-images.githubusercontent.com/1336626/201086410-792a0bde-1cad-41cc-b982-51662ba821bb.png)
![Code snippets](https://user-images.githubusercontent.com/1336626/201086416-c8b73407-5842-4c04-b089-0433a3dd420d.png)

**Comment by cmelchior** [comment]
I have seen the same issue, but only when rerunning apps on the Android Emulator, so I suspect it is a problem with the random generator reusing the same seed in those cases. It should not impact release apps, but we should probably still switch to SecureRandom (which isn't available in Kotlin Multiplatform, but we should be able to get platform implementations for it)
