### ISSUE TITLE
@LinkingObjects doesn't work with EmbeddedRealmObject

### ISSUE THREAD

**Issue by sirambd** [realm/realm-kotlin#1134]
**Description**
Since version **1.5.0** the `Backlinks` have been added and it's a great news but since the delegate function is waiting for a `RealmObject` then it doesn't work with the `EmbeddedRealmObject` class, but it works with `RealmObject` class.

**Delegate function** 
```kotlin
public operator fun getValue(
        reference: RealmObject,
        targetProperty: KProperty<*>
    ): RealmResults<T>
```

**Comment by clementetb** [comment]
Hi @sirambd, yes, we detached the development of backlinks on embedded objects from the regular objects.

The following PR provides a form of backlinks that might be useful for your use case: https://github.com/realm/realm-kotlin/pull/1141

**Comment by sirambd** [comment]
Oh nice, I can confirm that this is the answer to my problem.
Thank you @clementetb
