### ISSUE TITLE
Extend `@PersistedName` annotation to apply to classes

### ISSUE THREAD

**Issue by elle-j** [realm/realm-kotlin#1138]
Similar to `@PersistedName` for fields (see #590), we should provide the option of mapping Kotlin class names to their underlying (persisted) name.

```kt
@PersistedName(name = "myPersistedName")
class Example : RealmObject {
    // ...
}
```

Other API's will also be affected by this:

* `RealmClass` should return the persisted name, not the public (Kotlin) name.
* RQL queries should support both the persisted and public names.

TODO:

// Step 1

[ ] Add a `CLASS` annotation target to `PersistedName.kt`.
[ ] Modify `AccessorModifierIrGeneration.modifyPropertiesAndCollectSchema` to account for persisted values (perhaps no changes needed here).
[ ] Modify `RealmModelSyntheticPropertiesGeneration` (see `addSchemaMethodBody()` where `irClass.name.identifier` is used, maybe other places as well).
[ ] Validate that persisted and public names are a unique in the Realm. They are not allowed to overlap. This check should happen at compile time.
[ ] Verify in Realm Studio that schema is modified correctly.

// Step 2

[ ] Make sure that `RealmClass` returns the persisted name, not the public (Kotlin) name in the model class.

// Step 3

[ ] Verify that queries can use both persisted and public names in queries.

**Comment by lukaspieper** [comment]
Hello,

may I ask if you have a schedule for this issue? For properties this has been possible for some time now, but without support for classes the feature doesn't really feel complete yet. This is the last feature I'm missing to complete the migration from realm-java.

Would be very cool if this could complete the existing part in near future.

Thanks a lot.

**Comment by rorbech** [comment]
Hi @lukaspieper. Thanks for the feedback, we are aware that this is a key point for some to migrate. Though it is indeed in our near future roadmap, the priorities and timeline are not fully laid out.

**Comment by ravitejaavv** [comment]
Hello,
Is there any update on this issue?

**Comment by ravitejaavv** [comment]
> Hi @lukaspieper. Thanks for the feedback, we are aware that this is a key point for some to migrate. Though it is indeed in our near future roadmap, the priorities and timeline are not fully laid out.

Its been more than 4 months. When do we expect this feature to be available ?

**Comment by rorbech** [comment]
It is a top priority item, but as always it is hard to predict an exact ETA. Would hopefully arrive within the next weeks
