### ISSUE TITLE
apply plugin: 'realm-android' kaptException 

### ISSUE THREAD

**Issue by FreedApe770** [realm/realm-kotlin#114]
i have a error by using kotlin realm 
![image](https://user-images.githubusercontent.com/19419886/104295321-4371fb80-54fb-11eb-8b18-9be29d0c7b30.png)

I create two model like this:
```java
open class ScheduleRealmModel(
    @PrimaryKey
    var scheduleId: Int = -1,
    var name: String = "",
    var subMedia: SubMediaRealmModel
) : RealmObject()
```
```java
open class SubMediaRealmModel(
    @PrimaryKey
    var id: Int = -1,
    var label: String = ""
) : RealmObject()
```

when I add these model into my project, the error occur, but when i remove `var subMedia: SubMediaRealmModel` from `ScheduleRealmModel`， the project build OK。

Detail：
Build.gradle(app)
```java
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: "androidx.navigation.safeargs.kotlin"
apply plugin: 'kotlin-kapt'
apply plugin: 'realm-android'
```

Build.gradle(Project)
```java
buildscript {
    ext.gradle_version = "4.0.2"
    ext.kotlin_version = "1.4.10"
    ext.navigation_Version = "2.2.2"
    ext.realm_version = "7.0.0"
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$gradle_version"
        classpath "io.realm:realm-gradle-plugin:$realm_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigation_Version"
    }
}
```

I hope to receive help!

**Comment by nhachicha** [comment]
Hi @FreedApe770 
`subMedia` can not be declared required (or notnull) you should instead use 
```Kotlin
var subMedia: SubMediaRealmModel? = null
```

_Please note this repo is for Kotlin Multiplatform, prefer creating an issue on the https://github.com/realm/realm-java one_

**Comment by FreedApe770** [comment]
@nhachicha 
Thank you! I also got it by several times attempts.
>Please note this repo is for Kotlin Multiplatform, prefer creating an issue on the https://github.com/realm/realm-java one
how to do, i am a newer for github.
