### ISSUE TITLE
Expected member name or ';' after declaration specifiers on iOS

### ISSUE THREAD

**Issue by swanwish** [realm/realm-kotlin#1153]
When I upgrade **realm-kotlin** to 1.5.0, iOS app will report the following error, the error message is like this:

```
Expected member name or ';' after declaration specifiers
```

There are two lines on `shared.h` caused the error:

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/10950677/204285181-f15f4916-3070-4ed8-a935-588e15d86394.png">

I think the reason is because **TRUE** and **FALSE** are keywords on Swift, I am not sure whether I didn't configure the Realm correctly or there already has the solution to solve the problem.

**Comment by rorbech** [comment]
Hi @swanwish. I have tried to run our sync sample in https://github.com/realm/realm-kotlin-samples/tree/main/MultiplatformDemoWithSync with 1.5.0 on iOS and I don't get any issues. Could you try to elaborate about your project configuration and what and how you are exposing these symbols?

**Comment by swanwish** [comment]
Hi Rorbech,

Thanks for your quick response, and I find the cause of the issue was that I used the ObjectId introduced in Realm 1.5.0 like below:

> Added support for BsonObjectId and its typealias org.mongodb.kbson.ObjectId as a replacement for ObjectId. io.realm.kotlin.types.ObjectId is still functional but has been marked as deprecated.

In your demo, the model entity `Counter` has no ObjectId property, and after I remove the ObjectId in my demo, it can compile either, the following is my model definition.

```
package com.swanwish.kmmrealm.models

import io.realm.kotlin.types.RealmObject
import io.realm.kotlin.types.annotations.PrimaryKey
import org.mongodb.kbson.ObjectId

class Item() : RealmObject {
    @PrimaryKey
    var _id: ObjectId = ObjectId()
    var isComplete: Boolean = false
    var index: Long = 0
    var thread: String = ""
}
```

Can you help to check this? 

Thanks very much!

**Comment by rorbech** [comment]
Hi @swanwish. Thanks for input. Seems to be an issue with the BSON library and not the Realm library itself. I have created an issue for this in https://github.com/mongodb/kbson/issues/9
