### ISSUE TITLE
SubscriptionSet::waitForSynchronization doesn't seem to work properly

### ISSUE THREAD

**Issue by sebdomdev** [realm/realm-kotlin#1158]
With version 1.5.0 of the realm kotlin sdk, when using partial sync, SubscriptionSet::waitForSynchronization seems to have some unintended behavior:
The objects are not returned in the corresponding query until the timeout is reached.
So if waitForSynchronization(10.seconds) is used, the objects will be returned after 10 seconds. If waitForSynchronization is used without any arguments, they never return (because the default value is Duration.INFINITE).

Example:

```
val subscriptions = realm.subscriptions

val query = realm.query(MyClass::class)
subscriptions.update {
    add(query)
}
subscriptions.waitForSynchronization(10.seconds)
query.asFlow().collect {
   // This is not called with the result set until 10 seconds have passed
}
```

**Comment by cmelchior** [comment]
Hi @sebdomdev 

I tried to reproduce this, but from what I can tell, things seem to work.

Keep in mind that `subscriptions.waitForSynchronization(10.seconds)` is a suspend function, so it will block until it either completes or the 10 seconds are done, so I suspect something else is wrong.

Have you verified you are not getting an error somewhere, either in the `SyncSession.errorHandler` or in `Subscription.errorMessage`?

**Comment by sebdomdev** [comment]
I didn't see any errors and it worked fine in earlier sdk versions.

**Comment by cmelchior** [comment]
Is it something you can reproduce?
