### ISSUE TITLE
Strange behavior with RealmInstant.now() on iOS

### ISSUE THREAD

**Issue by hemantgokhale** [realm/realm-kotlin#1182]
I am seeing some strange behavior with RealmInstant.now() on iOS. It works correctly on Android, but on iOS RealmInstant.now().epochSeconds is always 9223372036854775807. I am new to both KMM and Realm and probably doing something wrong, but cannot figure out what.

I created a new KMM App using Android Studio (2021.3.1 Patch 1), added realm dependencies to the build files, then changed the code in function greet() to the following:
```
fun greet(): String {
        val now = RealmInstant.now().epochSeconds
        println(now)
        return "Hello, ${platform.name}!\nnow: $now"
 }
```

Here are some other details:
Realm version: 1.5.1
Kotlin version: 1.7.20
iOS Simulator: iPhone 14 - iOS 16.2

**Comment by edualonso** [comment]
Hi @hemantgokhale. I can reproduce the behaviour you're reporting. We will look into it.
