### ISSUE TITLE
How to handling realm close ?

### ISSUE THREAD

**Issue by BobFactory** [realm/realm-kotlin#1185]
Hi, 

I have an android project and I use the realm-kotlin latest frozen architecture. 
I wanted to get some thoughts on closing of realm. I have a singleton class that created one realm instance that is used by the dao class to present data to the user. Since entire app is dependent on the data I went with this approach of creating the realm instance and storing the single instance. 

```kotlin
class Database {

   private val schema: Set<KClass<out BaseRealmObject>> = setOf()

    private val configuration = RealmConfiguration.Builder(schema)
        .schemaVersion(1)
        .deleteRealmIfMigrationNeeded()
        .name(REALM_NAME)
        .build()

    private val realm by lazy { Realm.open(configuration) }

    fun get() = realm
}

```

I saw in the documentation that `realm.close()` method is used for closing realm. I wanted to check if my approach causes any memory leaks or is a heavy object to hold on to for longer periods (not that long though possibly 5 mins of user activity). 

I use a DI to create this `Database` class a singleton across the app and so I am hoping that when the app is terminated the realm is released from memory. 

Do you suggest that I should rather open realm instance when each DAO operation is invoked instead? like how `Realm.getInstance()` was used in java SDK?

**Comment by cmelchior** [comment]
With the architecture refactore, the approach from Realm Java should no longer be needed and just keeping the Realm open for the entire lifetime of the app should be fine.
