### ISSUE TITLE
Boolean index produces error

### ISSUE THREAD

**Issue by mobiletoly** [realm/realm-kotlin#1193]
Kotlin multiplatform Realm SDK version: 1.5.1
Gradle plugin: io.realm.kotlin:gradle-plugin:1.5.1

Example:
```
class ActivityDoc() : RealmObject {
    @Index var myFlag: Boolean = true
    ...
}
```

produces error: **[Realm] Indexed key myFlag is of type Boolean but must be of type [Byte, Char, Short, Int, Long, String, RealmInstant, BsonObjectId, ObjectId, RealmUUID]**

while documentation states that Boolean is supported to be indexed field:

https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/schemas/index/

so who is wrong? documentation? or is it a bug in SDK and Boolean type must be supported for indexing?

**Comment by rorbech** [comment]
This seems to be our compiler plugin that erroneously guards against marking boolean properties as indexed. I have created #1197 to fix this.
