### ISSUE TITLE
Realm version 23 support

### ISSUE THREAD

**Issue by Reedyuk** [realm/realm-kotlin#1214]
When using latest release of realm kotlin, it is unable to open a realm file that is opened with the latest version of realm studio.

```
RealmCoreException([RLM_ERR_OTHER_EXCEPTION]: Opening Realm files of format version 23 is not supported by this version of Realm)
```

When will there be support for such a database?

**Comment by cmelchior** [comment]
Hi, the latest release of Realm Studio should support these files: https://studio-releases.realm.io/v13.0.0

**Comment by Reedyuk** [comment]
@cmelchior the issue is, i opened the realm in the latest realm studio, then when i try to open the realm file in my application, using the latest realm dependancy, it throws this error.

**Comment by cmelchior** [comment]
Ah, sorry, I misunderstood you there.

We have a `1.6.0-SNAPSHOT` that supports it already. Currently it looks like it will be released as as stable version this week.

**Comment by Reedyuk** [comment]
I might be doing something wrong, i added the sonatype snapshot repo but its unable to find 1.6.0-SNAPSHOT
Could you clarify that its there?

**Comment by rorbech** [comment]
Hi @Reedyuk. The `1.6.0-SNAPSHOT` is indeed available at https://oss.sonatype.org/content/repositories/snapshots/io/realm/kotlin/library-base/1.6.0-SNAPSHOT/ 

But the snapshot is not available through Gradle plugin portal, so you need to manually add it to the classpath. Maybe have a look at the instructions in https://github.com/realm/realm-kotlin#using-snapshots

**Comment by edualonso** [comment]
@Reedyuk remember you need to add the URL to the snapshot repo twice in the top-level Gradle file:
```
buildscript {
    repositories {
        maven {
            url = uri("https://oss.sonatype.org/content/repositories/snapshots")
        }
    }
    dependencies {
        classpath("io.realm.kotlin:gradle-plugin:1.6.0-SNAPSHOT")
    }
}
allprojects {
    repositories {
        maven {
            url = uri("https://oss.sonatype.org/content/repositories/snapshots")
        }
    }
}
```

**Comment by Reedyuk** [comment]
@edualonso - i see that 1.6.0 is live now, but it still says it doesn't support version 23

**Comment by Reedyuk** [comment]
Scrap that, its working.
