### ISSUE TITLE
Different versions in documentation

### ISSUE THREAD

**Issue by Yeechaan** [realm/realm-kotlin#1224]
Hello there!

In [documentation](https://www.mongodb.com/docs/realm/sdk/kotlin/install/kotlin-multiplatform/#installation) ("Kotlin SDK -> install -> kotlin multiplatform"), the realm.kotlin version is different between plugins(1.4.0) and commonMain dependencies(1.5.0).
The project synced in the "build.gradl.kts" file, but failed when I tried to build it.

Most of the developers might know what the problem is and follow the latest version.
But for the developers who just started programming, they might be confused.

Thank you for your support.

**Comment by edualonso** [comment]
The fix in the documentation has been deployed.
