### ISSUE TITLE
Native crash when run on iOS

### ISSUE THREAD

**Issue by tarasmorskyi-mediamonks** [realm/realm-kotlin#1248]
As iOS is still not using the shared code test part wasn't maintained and now as we are moving forward everything got updated `Realm` from `1.0.0` to `1.6.0` and `Kotlin` from `1.7.10` to `1.8.0`. 
On old versions everything runs fine with no issues, but not when running on Realm `1.1.0+` (went through try and fail to find when it stopped working) which means it's probably connected to `new memory management` and totally makes sense looking on assembly crash. Unfortunately I couldn't reproduce the issue on sample project so I have to roughly describe where it's crashing. 
It basically happens on app launch as it's data from very first request for app settings stored into Realm. Part is launched in `Repo` init part injected through Koin and coroutine is launched with this internal scope `CoroutineScope(SupervisorJob() + Dispatchers.Default)`. When I do copyToRealm it's crashes with stacktrace shown on screenshots shared in comments. I've tried using some fake object thinking maybe it's Ktor doing something to coroutine state but still no. 

Could you share what is happening in crashed part so I could find what is causing it?

**Comment by tarasmorskyi-mediamonks** [comment]
<img width="1728" alt="Screenshot 2023-01-27 at 14 13 39" src="https://user-images.githubusercontent.com/50660533/215098162-1846467e-69f8-4507-be20-caf3f6900d17.png">
<img width="1728" alt="Screenshot 2023-01-27 at 14 14 03" src="https://user-images.githubusercontent.com/50660533/215098177-bf6491e4-81ba-4ae8-9265-6c477c1939c0.png">
<img width="1728" alt="Screenshot 2023-01-27 at 14 14 09" src="https://user-images.githubusercontent.com/50660533/215098195-fbda0995-efe4-48a6-9d29-6625ded43f77.png">
<img width="1728" alt="Screenshot 2023-01-27 at 14 14 12" src="https://user-images.githubusercontent.com/50660533/215098209-e97a9f82-8164-48e1-aa98-68ad0e521c19.png">
<img width="1728" alt="Screenshot 2023-01-27 at 14 14 15" src="https://user-images.githubusercontent.com/50660533/215098224-372278ad-bed4-4be5-94b5-19257e71e866.png">
<img width="1728" alt="Screenshot 2023-01-27 at 14 14 19" src="https://user-images.githubusercontent.com/50660533/215098238-8593b022-bfca-4539-9ffc-9546ccea560c.png">
<img width="1728" alt="Screenshot 2023-01-27 at 14 14 22" src="https://user-images.githubusercontent.com/50660533/215098255-368b38a7-b4c0-4990-848b-8a2becdb6f78.png">

**Comment by tarasmorskyi-mediamonks** [comment]
![Screenshot 2023-01-27 at 14 13 39](https://user-images.githubusercontent.com/50660533/215098865-9f3db9ac-1e3d-4fd0-8710-ab3c4ee6878d.jpg)

**Comment by tarasmorskyi-mediamonks** [comment]
![Screenshot 2023-01-27 at 14 13 39](https://user-images.githubusercontent.com/50660533/215100298-57228a12-aa63-4239-a7fc-d99684b6e9bf.jpg)
![Screenshot 2023-01-27 at 14 14 03](https://user-images.githubusercontent.com/50660533/215100313-8815b8c1-1071-40b4-9b6c-b2292ccddc94.jpg)
![Screenshot 2023-01-27 at 14 14 09](https://user-images.githubusercontent.com/50660533/215100329-20599b49-d728-4e54-8f20-e05e4cfde030.jpg)
![Screenshot 2023-01-27 at 14 14 12](https://user-images.githubusercontent.com/50660533/215100342-20c33380-b9ab-4525-a0bd-92041c0242dc.jpg)
![Screenshot 2023-01-27 at 14 14 15](https://user-images.githubusercontent.com/50660533/215100354-030e5de2-bbb4-422e-85e8-069627e5db01.jpg)
![Screenshot 2023-01-27 at 14 14 19](https://user-images.githubusercontent.com/50660533/215100371-8339f1f8-8292-43f8-a082-d700da40e420.jpg)
![Screenshot 2023-01-27 at 14 14 22](https://user-images.githubusercontent.com/50660533/215100388-3e9afdfe-ee1c-4d99-8f75-c6901f122a7b.jpg)

**Comment by clementetb** [comment]
Thanks for reporting the issue. We would need more context to investigate the issue. Could you share some details about the model you are trying to write in the Realm?

Did the new memory model work on your project when you used Realm `1.0.0` and Kotlin `1.7.10`? If yes, could you keep updating the Realm dependency until you find the one that breaks your IOS app?

**Comment by tarasmorskyi-mediamonks** [comment]
@clementetb thanks for replying. 

While I was trimming all the possible fields to share it here I've found what is causing issue. It's all because of embedded objects. [Here](https://github.com/tarasmorskyi-mediamonks/realm-issue-1248 ) is sample project which has this issue and [here](https://github.com/tarasmorskyi-mediamonks/realm-issue-1248/blob/main/shared/src/commonMain/kotlin/com/example/myapplication/TestRealmClass.kt) is realm model

**Comment by tarasmorskyi-mediamonks** [comment]
I tried the repo from above again and it had a readable mistake as field is not nullable but should be. It's not the case for the actual project which means I still cannot reproduce it on small project.
I pushed replication of model from actual project [here](https://github.com/tarasmorskyi-mediamonks/realm-issue-1248/blob/main/shared/src/commonMain/kotlin/com/example/myapplication/Settings.kt)

**Comment by tarasmorskyi-mediamonks** [comment]
reguarding the question above. Yes, new MM was in place before and only change of Realm version caused an issue.

**Comment by rorbech** [comment]
Hi @tarasmorskyi-mediamonks.  I have tried your reproduction project and cannot reproduce the error. Can you try to elaborate on the above comments about where and when you can reproduce it?

**Comment by tarasmorskyi-mediamonks** [comment]
hey @rorbech , it was a false alarm and thats what I ment with my last message. I have tried my shared code on empty ios project and it worked fine. I have feeling there is connection to incompatiblity with iOS libraries like RealmSwift or Lokalise. Are there any requirements on what versions are compatible to each other? I mean RealmKotlin and RealmSwift.

**Comment by tarasmorskyi-mediamonks** [comment]
I mention Lokalise above because I know they use Realm in Android lib so assume it's the same for iOS

**Comment by rorbech** [comment]
Hi @tarasmorskyi-mediamonks. We don't support running multiple SDK at the same time, so if that is what you are doing then that is probably the root of you issue. You should however be able to read a realm file written with one SDK with another SDK as long as it support the realm file format version written by both of them (the realm file format of the SDKs can be seen in the CHANGELOG). If you need more input please elaborate a bit more on your app infrastructure or make a reproduction project as it is quite hard to reason about without all the details.

**Comment by tarasmorskyi-mediamonks** [comment]
@rorbech what do you mean with not supporting multiple SDK at the same time? Wasn't it what fixt [this](https://github.com/realm/realm-kotlin/issues/280) issue I reported long time ago?

**Comment by tarasmorskyi-mediamonks** [comment]
@rorbech after few confusing messages (sorry) above I have a broken sample build now. Looks like issue is related to version incompatibility. As I wrote above, when I tried with actual iOS project it started braking with Realm 1.1.0 because branch I used for iOS sample was outdated and used quite old RealmSwift. Now when I have the test project it's not a problem to update Pods and I could play with versions. In the end I received that current version of RealmSwift(10.34.1) isn't compatible with current version of RealmKotlin(1.6.0). It wouldn't be a problem to drop to RealmKotlin 1.5.2 as there was nothing in Changelog I'm using, but it doesn't work with Kotlin 1.8.0 which brought quite useful things like ObjCName. 
I updated a repo:
Broken - [link](https://github.com/tarasmorskyi-mediamonks/realm-issue-1248/tree/broken)
Working - [link](https://github.com/tarasmorskyi-mediamonks/realm-issue-1248/tree/working)

**Comment by cmelchior** [comment]
Hi @tarasmorskyi-mediamonks 

Can you describe the exact steps to reproduce this? I tried to download your broken project, but it seems to work for me. I opened the iOS project in XCode 14.2 and ran it on iPhone 14 pro simulator.

**Comment by tarasmorskyi-mediamonks** [comment]
This is weird. It's  exactly what I do. Everything I did is `pod install` and run on Iphone simulator with Xcode 14.2 as well. 
Could you double check if it's the branch with Kotlin 1.8.0, Realm-kotlin 1.6.0 and RealmSwift added to pods? For me just adding RealmSwift to pods while I'm on RealmKotlin 1.6.0 is breaking the app. It builds but crashes right after launch

**Comment by cmelchior** [comment]
@tarasmorskyi-mediamonks I noticed that there is a only a `iosApp/Podfile` in the `working` branch, but it doesn't exist in the `main` branch. Did you forget to commit it to `main`?

**Comment by tarasmorskyi-mediamonks** [comment]
@cmelchior `main` branch wasn't updated and should be ignored. Only `working` and `broken` branches should be checked and the latest one fails for me as it has RealmSwift in Pods

**Comment by clementetb** [comment]
We can reproduce the issue with your repo @tarasmorskyi-mediamonks. It fails as in the examples above:

`EXC_BAD_ACCESS (code=1, address=0x18)`

**Comment by clementetb** [comment]
The issue seems related to the cocoapods configuration in KMM. If you replace it with the one used in the Kotlin multiplatform demo it works fine.

I have created a PR against your demo project that shows this issue: https://github.com/tarasmorskyi-mediamonks/realm-issue-1248/pull/1

**Comment by tarasmorskyi-mediamonks** [comment]
@clementetb I finally had a chance to ask coworkers to try it on their machine (one on M1 one on Intel) and it works. Which means it's an issue on my machine and not with Realm. 
Thanks

**Comment by tarasmorskyi-mediamonks** [comment]
@ruijfcanas the issue I had was cause by migration from Intel Macbook to M1 with Apples migration tool which copied all the installed packages no matter if there is a version for M1 already available. For me reinstalling all the iOS needed things fixed it (Xcode, Ruby, Pods whatever else, ask iOS devs)

**Comment by ruijfcanas** [comment]
@tarasmorskyi-mediamonks I have a Mac with an Intel chip and I've also tested my code on a M1 Mac and the result is the same. I did not perform any migration, so that can't be the issue on my side.

**Comment by clementetb** [comment]
@ruijfcanas Are you able to run any of our sample projects? 

If you can run them it would mean that there is an issue in your project setup, whereas if not, it means that there is some issue in your environment.

**Comment by ruijfcanas** [comment]
@clementetb yap, the first time I succeeded but I noticed that the Kotlin version was not >=1.8.0. I then proceed to bump Kotlin version and the Realm version as well and it crashed. 

<details>
<summary>❌ Screenshot with logs from Xcode</summary>

![Screenshot 2023-06-02 at 16 42 27](https://github.com/realm/realm-kotlin/assets/58333456/7c772a1c-fcaa-4e33-9fe5-3f0ad366d8c1)
</details>

<details>
<summary>❌ Screenshot with error on simulator</summary>

![Screenshot 2023-06-02 at 15 29 38](https://github.com/realm/realm-kotlin/assets/58333456/968181c3-0bc3-4f30-8d4a-91ba9fe80eb9)
</details>

Only thing I did was update the Kotlin version to 1.8.10, used the latest version for Realm and then run the project on a simulator.

**Comment by ruijfcanas** [comment]
So, I ended up finding out what the issue was. The issue was with Realm's version in my iOS app, which left me confused.
I have my iOS app working with Realm, and then I have my shared module that also works with Realm. Each module handles its cache independently, so what could be the logical reason for this?
Reading this [post](https://slack-chats.kotlinlang.org/t/10027549/hi-there-we-have-a-native-ios-app-using-realm-swift-and-we-v) with an answer from @cmelchior has made me even more confused 😅
