### ISSUE TITLE
Create Kotlin packages on Bintray

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#125]
In order to promote our OJO packages to a proper release on Bintray, it looks like we need to manually create each package on Bintray and link it to JCenter: https://www.jfrog.com/confluence/display/BT/Managing+Packages

Unfortunately due to how KMP organizes packages, we have quite a lot: 
![image](https://user-images.githubusercontent.com/406066/105160870-05836180-5b11-11eb-8034-e72a6bb88f63.png)

**Comment by rorbech** [comment]
Closes as superseded #151
