### ISSUE TITLE
Native Sync Thread is leaking

### ISSUE THREAD

**Issue by astatio** [realm/realm-kotlin#1290]
The number of realm threads has increased exponentially after 1.6.0. In one of my threads dumps that I made to check why my bot was becoming unresponsive i saw 8435 threads in a single realm db file! The thread dump was also over 23MB. This did not happen before. It seems there's a serious memory leak problem. 

I would like to highlight that this comes after the following issue https://github.com/realm/realm-kotlin/issues/1007 was solved and happens under the same conditions: a realm with lots of writes under short amounts of time (3 per 5s, for example)

**Comment by cmelchior** [comment]
Hi @astatio. That doesn't right. It is true that we changed how our threads are managed and currently there is a known leak for Synced Realms, but it should only leak a single thread.

Are you by any chance opening and closing Realms during the writes?

**Comment by astatio** [comment]
It appears that is correct i do indeed call a method that opens and closes the same Realm file to perform a query while still having the same Realm file open. Is that what causes the problem? If so, shouldn't it throw an Exception?

**Comment by cmelchior** [comment]
Yes, that would cause this problem. We will be working on a fix, but note, that in Realm Kotlin (unlike Realm Java), you don't really need to open and close the Realm. You can just open it once and keep it open for the lifetime of the app.
