### ISSUE TITLE
Encrypted databases migration

### ISSUE THREAD

**Issue by damiandzierzak** [realm/realm-kotlin#1302]
Hi, I plan to migrate data from Java SDK to Kotlin SDK. My databases are encrypted and I'm wondering if it is possible to migrate the old database into the new one with a different `encryptionKey`? Is there any documentation of that process?

**Comment by cmelchior** [comment]
I'm not 100% sure if we have written docs anywhere, but you can do something like this:

```
val config1 = RealmConfiguration.Builder(schema).encryptionKey(encryptionKey1).name("original.realm").build()
val config2 = RealmConfiguration.Builder(schema).encryptionKey(encryptionKey2).name("copy.realm").build()

var realm = Realm.open(config1)
realm.writeCopyTo(config2)
realm.close()

// Copy with a new encryption key
realm = Realm.open(config2)
```

**Comment by damiandzierzak** [comment]
What about the schema because in the Java SDK it wasn't required? Is there any hack to avoid providing it or should I copy all files and transform them to the Kotlin SDK?
