### ISSUE TITLE
Does a realm need to be manually closed.

### ISSUE THREAD

**Issue by AntsyLich** [realm/realm-kotlin#1321]
I am working on an app and by it's odd nature I need to work with multiple realm. So I'm planning on opening a realm in  function bodies with current config. My question is in this case will the realm object need manual closing in the end. Below is an example code snippet for better understanding.
```kt
suspend fun insertFoo(foo: Foo, config: CustomConfig) {
    val realm = Realm.forConfig(config)

    // Inserting with realm

   realm.close() // Is this necessary??
}
```

**Comment by clementetb** [comment]
Hi, it is not necessary but instantiating a Realm on each function call would be a waste of resources. It would be better to keep a single instance for each Realm, and pass it to the `insertFoo` function:

```kotlin
suspend fun insertFoo(foo: Foo, realm: Realm) {
    // Inserting with realm
}
```

In Realm-Kotlin there are no thread confinement restrictions.

**Comment by clementetb** [comment]
Looks ok, you might need to close the old instance before returning the new realm instance.
