### ISSUE TITLE
Is not possible to have google sign in working for bot iOS app and Android app at the same time?

### ISSUE THREAD

**Issue by danielgabor99** [realm/realm-kotlin#1326]
On the documentation, it is stated that the iOS app should work if we add the client web application configuration, but this is not true. https://www.mongodb.com/docs/atlas/app-services/authentication/google/#std-label-auth-google-configuration
Is there any workaround for this?

Same issue reported here:
https://github.com/realm/realm-swift/issues/8111
https://github.com/realm/realm-swift/issues/7506

**Comment by clementetb** [comment]
Did you run into this same issue? Can you share some context on how you are doing the authentication and token handling? It would be great if you could share some code or even better an example project.

**Comment by danielgabor99** [comment]
yes, I run in the same issue unfortunately, as the posts above.

-Passing the GCP Web clientId to Google results in a error from the sign in page: `"Authorisation Error" 400: Custom scheme URIs are not allowed to 'WEB' client type.`
-Passing the GCP iOS credential allows the Google sign in page to work, and returns an idToken, but then passing that to Realm gives the error: `47 - invalid id token: ‘aud’ must be a string containing the client_id`

**Comment by clementetb** [comment]
On which platform are you getting this error: 
> Passing the GCP Web clientId to Google results in a error from the sign in page: `"Authorisation Error" 400: Custom scheme URIs are not allowed to 'WEB' client type.`

**Comment by danielgabor99** [comment]
On iOS, for the Android I can use the WebClientID, but for iOS I get this error` "Authorisation Error" 400: Custom scheme URIs are not allowed to 'WEB' client type.`

**Comment by clementetb** [comment]
Have you followed the official [Google Sign-In for iOS Integration Guide](https://developers.google.com/identity/sign-in/ios/start-integrating)?

**Comment by danielgabor99** [comment]
Yes, I did.

The android version works fine using the Web application type OAuth client ID.
The problem its only on iOS.

**Comment by clementetb** [comment]
Have you tried this workaround: https://github.com/realm/realm-swift/issues/7506#issuecomment-964225769
