### ISSUE TITLE
Flaky test: objectNotificationsCausesTracking – io.realm.kotlin.test.shared.VersionTrackingTests

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#1348]
`
java.lang.AssertionError: VersionInfo(main=VersionData(current=VersionId(version=2), active=[VersionId(version=2)]), notifier=VersionData(current=VersionId(version=10), active=[VersionId(version=7)]), writer=VersionData(current=VersionId(version=10), active=[])) expected:<6> but was:<2>
`

https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-1347/7/tests

We are enabling TRACE level logs for the test to have better information if this happens again.

**Comment by rorbech** [comment]
I suspect it is just because the garbage collector frees the sample results because the `samples` variable is optimized away after usage, but would be nice to confirm ... and then make it deterministic 😅

**Comment by cmelchior** [comment]
Another failure here: https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-1354/11/tests
