### ISSUE TITLE
Add flow for user changes

### ISSUE THREAD

**Issue by sebdomdev** [realm/realm-kotlin#1349]
### Problem

The realm java sdk as well as the realm swift sdk both have methods of getting notified when a user changes.

In the realm java sdk, there is an AuthenticationListener that you [can register with the App](https://github.com/realm/realm-java/blob/1f2883651df9d3a78efe44d2febb963a7e420ffb/realm/realm-library/src/objectServer/java/io/realm/mongodb/App.java#L435) that gets notified when a user logs in or out.

### Solution

It would be useful if a similar functionality exists for the realm kotlin sdk. For example, a flow that emits User objects when a new user gets logged in would be great.

### How important is this improvement for you?

I would like to have it but have a workaround

### Feature would mainly be used with

Atlas App Services: Auth or Functions etc

**Comment by cmelchior** [comment]
Thanks for reporting this. This issue is already being tracked here: https://github.com/realm/realm-kotlin/issues/1349, but I agree that exposing it as a Flow will probably make more sense in Kotlin.

Folding this into #1349 as a duplicate.
