### ISSUE TITLE
Searching in tables with user-defined types

### ISSUE THREAD

**Issue by Azamature1719** [realm/realm-kotlin#137]
I use the Realm database for my mobile app. Some database classes contain fields of user-defined types, for example, the DataHarvestedRecordManager class contains fields of the ProductClassifierObject, CharacteristicClassifierObject and ContainerRecordManager types, which were implemented by me.

```
open class DataHarvestedRecordManager: RealmObject() {
@PrimaryKey
    var uuid: String = UUID.randomUUID().toString()
    var currentDate: Date = Date()
    var desc: String? = ""
    var product: ProductClassifierObject? = null
    var characteristic: CharacteristicClassifierObject? = null
    var container: ContainerRecordManager? = null
    var quantity = 0.0
    var quantityAcc = 0.0
}
```
To search in the table, I implement the fetch function, which parameters are variables of user-defined types. Inside my fetch() function, I use the Realm equalTo() function. However, the equalTo() parameters can only be of built-in data types.

That's why I have to search by the ID-field of the passed objects, and not by the objects themselves, and use the following construction:

```
fun DataHarvestedRecordManager.fetch(product: ProductClassifierObject, 
characteristic: CharacteristicClassifierObject?, 
container: ContainerRecordManager?):DataHarvestedRecordManager? 
{
   val realm = Realm.getDefaultInstance()
   val objects = realm.where<DataHarvestedRecordManager>()
    .equalTo("product.uuid", product.uuid).and()
    .equalTo("characteristic.uuid", characteristic.uuid).and()
    .equalTo("container.uuid", container.uuid)
    .findFirst()

   realm.close()
   return objects
}
```

Are there ways to search in Realm tables by objects of user-defined types, rather than by their fields of built-in types?

**Comment by rorbech** [comment]
Please note that this repository is for our newly started `realm-kotlin` SDK. Your question concerns `realm-java` which is tracked at https://github.com/realm/realm-java.
 
But, no, you cannot pass user defined types to the query system, so you would have to used linked properties like you do and pass in the primitive types.

If you need more input, please create an issue in the repository for `realm-java` at https://github.com/realm/realm-java.
