### ISSUE TITLE
Realm does not support properties of this type (Date)

### ISSUE THREAD

**Issue by jsuffolk** [realm/realm-kotlin#1378]
### How frequently does the bug occur?

-- select --

### Description

Using Realm Kotlin 1.8

Builds fail with "Realm does not support persisting properties of this type" on Date data type (Java.Util.Date)

The realm documentation suggests the Date data type should be supported:
https://www.mongodb.com/developer/products/realm/realm-data-types/#android-kotlin--new-realm-supported-data-types

### Stacktrace & log output

```shell
[Realm] Realm does not support persisting properties of this type. Mark the field with `@Ignore` to suppress this error.
```

### Can you reproduce the bug?

-- select --

### Reproduction Steps

class Whatever(): RealmObject
{
    var createdAt: Date = Date()
    var updatedAt: Date = Date()
}

### Version

1.8

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android SDK 33 Kotlin 1.8

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by clementetb** [comment]
@jsuffolk Unfortunately `Realm-kotlin` does not support `java.util.Date` yet. As a workaround, you could use `RealmInstant` and do any conversion yourself.

The documentation section https://www.mongodb.com/developer/products/realm/realm-data-types/#android-kotlin--new-realm-supported-data-types refers to the project `Realm-Java`.

**Comment by clementetb** [comment]
@jsuffolk 

We have put this PR that would allow to write delegates in your models to facilitate doing any type conversion:

```kotlin
class DateAdapter(
    private val realmInstantProperty: KMutableProperty<RealmInstant>
) {
    operator fun getValue(thisRef: Any?, property: KProperty<*>): Date {
        return Date(realmInstantProperty.call(thisRef).epochSeconds)
    }

    operator fun setValue(thisRef: Any?, property: KProperty<*>, value: Date) {
        realmInstantProperty.setter.call(thisRef, value)
    }
}

class Example : RealmObject {
    var realmInstant = RealmInstant.now()
    @Ignore
    var date: Date by DateAdapter(B::realmInstant)
}


```

**Comment by Baterka** [comment]
> 

Can this be used only if `var realmInstant` stays public? I tried with private field and it does not work. Thats a bummer.

**Comment by Baterka** [comment]
@clementetb 

Can this be used only if `var realmInstant` stays public? I tried with private field and it does not work. Thats a bummer.

**Comment by clementetb** [comment]
Unfortunately, the delegated properties must be public for the delegate.
