### ISSUE TITLE
Crash in copyToRealm.

### ISSUE THREAD

**Issue by darkan23** [realm/realm-kotlin#1409]
### How frequently does the bug occur?

Sometimes

### Description

I've got a weird crash when copyToRealm.

    open class PendingPhone : RealmObject {

          @PrimaryKey
          var pendingId: String = ""
          var client: Client? = null
          var dealtId: Long = 0
          var clientId: Long = 0
          var phoneType: PhoneType? = null
          var phoneColorType: PhoneColorType? = null
          var phoneOwnerType: PhoneOwnerType? = null
          var phoneNumber: String = ""
          var description: String? = null
          var creatingDate: Long = 0
          var syncDate: Long? = null
    }

I am trying to save the given object in Realm:

      val creatingDate = Instant.now().toEpochMilli()
      val newPhone = PendingPhone().apply {
         this.pendingId = pendingId
         this.debtor = debtor
         this.debtId = debtId
         this.debtorId = debtor.debtorId
         this.phoneType = phoneType
         this.phoneColorType = null
         this.phoneOwnerType = phoneOwnerType
         this.phoneNumber = phoneNumber
         this.description = description
         this.creatingDate = creatingDate
         this.syncDate = null
      }

      realmTemplate.executeInRealm { realm ->
         realm.copyToRealm(newPhone)
      }

     suspend fun <T> executeInRealm(code: (MutableRealm) -> T): = realm.writeBlocking {
        code.invoke(this)
    }

In this case, if you call findLatest before saving, as the error says, then after the error it will say that the object has not yet been created, use copyToRealm

What am I doing wrong??

### Stacktrace & log output

```shell
Stacktrace below :

java.lang.IllegalArgumentException: Cannot import an outdated object. Use findLatest(object) to find an up-to-date version of the object in the given context before importing it.
```

### Can you reproduce the bug?

-- select --

### Version

1.8.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

Android, v. 10

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by cmelchior** [comment]
Hi @darkan23 

This happens when you try to `copyToRealm` an already managed Realm Object that is outdated. Most likely, you are doing something like this:

```
// Create unmanaged person outside the write transaction
val person = Person("Jane Doe") // Create unmanaged person
person.child = realm.query<Child>("name == 'Tim'").first().find()!! // Reference a managed object

realm.write {
  // Copying the person here might throw the error you are seeing if the Realm progressed from the time you did the query.
  copyToRealm(person) 
}
```

Is it something like this you are doing?

**Comment by cmelchior** [comment]
Yes, that pattern is a problem. The reason it is a problem is that Realm Objects are versioned and thus might change once you enter a write transaction.

I.e. in your logic, you might read Client at version 1 and store it in your object, then, just before doing the write, another thread deletes that Client object.

Then when you enter the write, it is unclear what the correct behavior would be.

In cases like this, you basically have two options:

1) You can use `copyFromRealm()` on the `Client` object when you assign it to PendingPhone. That would work, but you might accidentally end up overwriting data you didn't want to.

2) Move all the logic inside the write transactions. You can only ever have active write transaction, so that will ensure we can guarantee data integrity. So something like this:

```
override fun createPendingPhone(
    dealId: Long,
    pendingId: String,
    phoneType: PhoneType?,
    phoneOwnerType: PhoneOwnerType?,
    phoneNumber: String,
    description: String?,
) {
    appScope.launch {
        // Always start transaction
        realmTemplate.executeInRealm { realm ->
            val client = realm.query<Client>("deals.dealId = $dealId")
            if (client == null || !client.isValid()) {
                log.warn("No client for deal with id $dealId! Can't save pending phone.")
                realm.cancelTransaction()
            } else {
                val creatingDate = Instant.now().toEpochMilli()
                val newPhone = PendingPhone().apply {
                    this.pendingId = pendingId
                    this.client = client
                    this.dealId = dealId
                    this.clientId = client.clientId
                    this.phoneType = phoneType
                    this.phoneColorType = null
                    this.phoneOwnerType = phoneOwnerType
                    this.phoneNumber = phoneNumber
                    this.description = description
                    this.creatingDate = creatingDate
                    this.syncDate = null
                }
                realm.copyToRealm(newPhone)
            }
        }
}
```

I would strongly recommend option 2.

**Comment by darkan23** [comment]
@cmelchior 

Thanks for the help!

**Comment by Igro182** [comment]
Hi! 
@cmelchior  thank you for the explanation. it solved my problem. 
I wanted to ask another question here. i think it's the right topic.

Is this a good example of using: 
```

            //Sample with find latest
            realmTemplate.write { realm ->
                val latestPerson = realm.findLatest(person)

                //do something with person, like add phone or anything

                realm.copyToRealm(latestPerson)
            }

```
Thank you!

**Comment by cmelchior** [comment]
@Igro182 

You don't need the last `copyToRealm`. Once you used `findLatest` you have access to the mutable Realm data and can just modify that object directly, so:

```
            //Sample with find latest
            realmTemplate.write { realm ->
                realm.findLatest(person)?.let {
                   name = "Jane Doe"
                }
            } ?: TODO("Handle the user not existing")
```

**Comment by Igro182** [comment]
@cmelchior Thank you! does it actually mean, this is another option to resolve the issue described by @darkan23 ? any of these options is preferable from performance or any other point of view?

**Comment by cmelchior** [comment]
Using `findLatest` is much better for performance, since you are only modifying the fields that changed.

**Comment by Igro182** [comment]
> Using `findLatest` is much better for performance, since you are only modifying the fields that changed.

Thank you @cmelchior !
