### ISSUE TITLE
Support generating Release Apple Frameworks 

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-kotlin#142]
Currently `capiMacosUniversal` and `capiIosArm64` tasks are using debug Monorepo builds 

maybe we can use 
```Kotlin
val framework = kotlin.targets.getByName<org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget>("ios").binaries.getFramework("CONFIGURATION")
 framework.buildType == NativeBuildType.RELEASE
```
To figure out if XCode is trying to use the build phase script (which runs the Gradle `packForXcode ` task) to build a Release framework. This is generally set via the `CONFIGURATION` flag from XCode

**Comment by cmelchior** [comment]
I ran into this. It means that if you just do 

```
cd examples/kmm-sample
./gradlew assemble
```

It will fail with the 

```
> Task :shared:linkReleaseFrameworkIosArm64
w: duplicate library name: io.realm.kotlin:cinterop-cinterop-realm_wrapper
e: Compilation failed: null
 * Source files:
 * Compiler version info: Konan: 1.4.30 / Kotlin: 1.4.30
 * Output kind: FRAMEWORK
e: java.lang.NullPointerException
```

Using 

```
./gradlew assembleDebug
```

Will work.
