### ISSUE TITLE
Realm swift got crash.

### ISSUE THREAD

**Issue by upscale-duc** [realm/realm-kotlin#1444]
### How frequently does the bug occur?

Always

### Description

Hi there, 

I use Realm Swift in my iOS native project and Realm Kotlin for a shared module that builds in Kotlin on multiple platforms. When trying to write data to Realm Swift I got an error (please check the screenshot below). 

![image](https://github.com/realm/realm-kotlin/assets/94164314/a37d66f8-8fb5-42ec-b534-79e2d371a414)

Here is some information.
 RealmSwift (~> 10.7)
 id("io.realm.kotlin") version "1.8.0"
 
 Realm Swift configuration:
 
```
 private lazy var configuration: Realm.Configuration = {
        var realmConfiguration = configurationBuilder()
        realmConfiguration.schemaVersion = USRealmManager.buildNumber
        realmConfiguration.fileURL = FileManager.default
                .containerURL(forSecurityApplicationGroupIdentifier: "group.com.myapp.stg")?
                .appendingPathComponent("myapp.realm")
        #if DEBUG
        realmConfiguration.encryptionKey = nil
        #endif

        return realmConfiguration
    }()
```

Realm Kotlin configuration

```
 constructor(realmObject: RealmObject) {
        val config = RealmConfiguration.Builder(schema = setOf(realmObject::class))
            .build()
        realm = Realm.open(config)
    }
```
    
I hope anyone can help me to sort it out. Thank you guys.

### Can you reproduce the bug?

-- select --

### Version

RealmSwift (~> 10.7)  id("io.realm.kotlin") version "1.8.0"

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

RealmSwift (~> 10.7)  and id("io.realm.kotlin") version "1.8.0"

**Comment by clementetb** [comment]
Are both Swift and Kotlin running on the same app? If so, are they writing to the same Realm file?

**Comment by upscale-duc** [comment]
@clementetb On iOS Swift, I've already set up a different realm file URL. but no luck.

**Comment by clementetb** [comment]
Currently, we do not support running both Swift and Kotlin SDKs on the same project, we have not tested it and cannot guarantee its behavior and correctness.

**Comment by clementetb** [comment]
If both SDKs have the same core version they might work on the same project, you can know by comparing changelogs. However, we don't guarantee its behavior and correctness.
