### ISSUE TITLE
Newly updated documents are not returned in a FullText Search query

### ISSUE THREAD

**Issue by luanrodrigsr** [realm/realm-kotlin#1458]
### How frequently does the bug occur?

Sometimes

### Description

Hey everyone!

I have noticed in a project that I am building for Windows, using the Realm Kotlin Multiplatform SDK, that almost every time I update a property of a document, which has the `@FullText` index annotation in it, directly in the database through the console or using the MongoDB Compass, the results returned in the client application with a query using the `TEXT` predicate often do not include the most recently updated documents, even if the predicate condition is true.

I'm not sure if I've missed something in the documentation, or if I'm doing something wrong. But so far in all the tests done I could identify this unexpected behavior. For such tests I'm using the `.asFlow()` function to track of updates, and even using the synchronous `.find()` function and restarting the application to track whether the results returned in the query include those which i've updated myself it is possible to identify that they are not always included.

This is the model of the Product object, which I am using in the database:

```kotlin
open class Product : Entity, RealmObject {
    @PrimaryKey
    override var _id: ObjectId = ObjectId.invoke()

    override var createdAt: RealmInstant? = null
    override var createdBy: String = ""
    override var createdById: ObjectId? = null

    @FullText
    var description: String = ""

    @FullText
    var brand: String = ""

    var unit: String = ""
    var secondaryUnit: String = ""
    var quantityPerUnit: Short = 1
    var unitCost: Float = 0f
    var totalCost: Float = 0f
    var category: String = ""
    var barcode: String? = null
    var sku: String = ""
    var archived: Boolean = false
}
```

Another information: I had already created some documents in my database before FullText Search query filter support was released.

I'll be happy to clarify more about this, apologizing in advance for any spelling errors in my text. 😅

Thank you all!

### Can you reproduce the bug?

Sometimes

### Reproduction Steps

**Considering that the database already contains documents with varied descriptions.**

1. Create a query using the TEXT predicate in the client;

> _Find all products that contains the word 'bovina' but not 'paleta' in their description_
> `val products = realm.query<Product>("description TEXT 'bovina -paleta'").asFlow()`

2. Update any document description property inserting the word 'bovina' in it through console or MongoDB Compass;
3. Keep listening for result changes;
4. See that some recently updated documents are not returned in the query.

### Version

1.10.1

### What Atlas App Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

Windows 11 amd64

### Build environment

IntelliJ IDEA version 2023.1.2 (Community Edition)
Gradle version 7.4

**Comment by clementetb** [comment]
Thanks for the report we are investigating the issue.

**Comment by clementetb** [comment]
Unfortunately, we have not been able to reproduce the issue. If data is not syncing it could be because:
1. object permission, check that the object matches the rules to allow synchronization,
2. the objects are outside the Sync subscriptions, check if the object is within the subscription set,
3. or there was some connectivity issue, but that would be temporary and objects would sync once resolved.

Could you please share the subscriptions, rules, and what data is being inserted in Atlas?

**Comment by luanrodrigsr** [comment]
Actually, the sync is working just fine. I can query all the recently updated documents in the local database using a simple `TRUEPREDICATE` filter without any problems.

```kotlin
realm.query(Product::class).find().forEach {
	println("Produto: ${it.description} da marca ${it.brand} com a ID: ${it._id}.")
}
```

I rechecked the code here and realized that my queries with the `TEXT` predicate are actually being performed with combined operators, could this be the problem?
```kotlin
productsFilter.initiate()
	.where {
		group {
			expression { "brand" equals "Corella" }
                        and { "description" contains "su" }
		} bind "pesquisa1"
		or { "description" search words { 
				include("bovina")
				exclude("paleta")
			}
		} bind "zero"
	}.sort("description", "brand")
```
The code above generates the following parameterized query String (i built it to help me create more flexible queries using Kotlin):
`(brand == $0 AND description CONTAINS[c] $1) OR description TEXT $2 SORT(description ASC, brand ASC)`

With the following arguments:
```
Index [0]: Corella
Index [1]: su
Index [2]: bovina -paleta (concatenated String)
```
It's this type of query that I'm actually having problems with. Sometimes it works, that is, the results are returned, but when I change the description of another product by inserting the word 'bovina', this same document may not be returned in the query, even if it has been synchronized with the client. I'm confused. 🤔

Anyway, I'll add more information below about the code I've been using.

At the moment, just for testing, I'm only inserting the description and brand of each product that is being created, the latter I add via the Data Services UI.

```kotlin
coroutineScope.launch {
	repository.addProduct(description = "Carne Bovina Picanha Fatiada KG")
		.onSuccess { response ->
			log.i { "${response.data.description} foi cadastrado com sucesso." }
		}
		.onError { response ->
			log.e { "Não foi possível adicionar o item." }
			log.e { response.message }
		}
}
```
```kotlin
suspend fun addProduct(description: String): Response<Product> {
        return add(newObject = Product().apply { this.description = description })
}
```
```kotlin
suspend fun add(newObject: T): Response<T> {
        // ...
	realm.write {
		this.copyToRealm(instance = newObject)
	}
	// ...
	Result.success(response = value,
        	error = if (database.isConnected) null else {
                        CommonError.UNKNOWN_ERROR
        	}
        )
	// ...
}
```

This is my sync configuration code:
```kotlin
val configuration = SyncConfiguration.Builder(
                    // TODO("Precisa implementar uma forma de tratar o banco de dados caso
                    //  acessado antes que o usuário esteja definitivamente conectado junto ao Atlas App Services.")
                    user = user,
                    schema = setOf(Product::class)
                ).maxNumberOfActiveVersions(
                    maxVersions = 5
                ).name(
                    // O diretório do banco de dados será em:
                    // System.getProperty("user.home")/${Project.Directory.ROOT_FOLDER}/services.
                    name = name
                ).initialSubscriptions(rerunOnOpen = false) { realm: Realm ->
                    this.add(realm.query<Product>(), name = "Produtos")
                    // FIXME("Essa parte do código precisa ser alterada.")
                }.build()
```

I'm using "Default roles and filters" in the database that has the Products collection:
```json
{
  "roles": [
    {
      "name": "owner-read-write",
      "apply_when": {},
      "document_filters": {
        "write": true,
        "read": true
      },
      "read": true,
      "write": true,
      "insert": true,
      "delete": true,
      "search": true
    }
  ]
}
```

Thank you for your attention!

**Comment by luanrodrigsr** [comment]
After doing some tests, I've noticed that **newly created objects** and their recently updated versions are actually being returned in the query I reported above. 

```kotlin
realm.query<Product>("brand == $0 AND description CONTAINS[c] $1) OR description TEXT $2 SORT(description ASC, brand ASC)", "Corella", "su", "bovina -paleta").asFlow()
```

It seems to me, and I'm not quite sure, that I'm having problems only with those items that were already in the database before FullText search support was released.

**Comment by clementetb** [comment]
Could you try with a query that only uses full-text search? Are all values being returned or are some of the pre-FTS being ignored?

We were not able to reproduce the issue ourselves. Could you reproduce the issue in a sample project?

**Comment by luanrodrigsr** [comment]
> Could you try with a query that only uses full-text search? Are all values being returned or are some of the pre-FTS being ignored?

Sure, i tested it today with a simple query using FTS and all values that match the condition are being returned, but i noticed that some values with the excluded word (`"-paleta"`) are being included too (by keeping track of the changes through a flow). 😕

```kotlin
realm.query<Product>("description TEXT $0 SORT(description ASC, brand ASC)", "bovina -paleta").asFlow() 
```

> Could you reproduce the issue in a sample project?

I created a simple project and tested it: [https://github.com/luanrodrigsr/FTSSample](url). 

Sometimes I can reproduce the issue by changing the description of the documents multiple times, but sometimes not.

**Comment by nhachicha** [comment]
Hi @luanrodrigsr I believe this was fixed, did you test it with the latest release?

**Comment by rorbech** [comment]
Just for reference. The fix was done in https://github.com/realm/realm-core/pull/6823.
