### ISSUE TITLE
serialization

### ISSUE THREAD

**Issue by helmysaeed** [realm/realm-kotlin#1461]
### How frequently does the bug occur?

Always

### Description

Exception in thread "AWT-EventQueue-0" kotlinx.serialization.SerializationException: Class 'UnmanagedRealmList' is not registered for polymorphic serialization in the scope of 'RealmList'.
To be registered automatically, class 'UnmanagedRealmList' has to be '@Serializable', and the base class 'RealmList' has to be sealed and '@Serializable'.
Alternatively, register the serializer for 'UnmanagedRealmList' explicitly in a corresponding SerializersModule.
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:102)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:114)
	at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:109)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:233)
	at kotlinx.serialization.json.internal.JsonStreamsKt.encodeByWriter(JsonStreams.kt:28)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:81)

### Stacktrace & log output

```shell
Exception in thread "AWT-EventQueue-0" kotlinx.serialization.SerializationException: Class 'UnmanagedRealmList' is not registered for polymorphic serialization in the scope of 'RealmList'.
To be registered automatically, class 'UnmanagedRealmList' has to be '@Serializable', and the base class 'RealmList' has to be sealed and '@Serializable'.
Alternatively, register the serializer for 'UnmanagedRealmList' explicitly in a corresponding SerializersModule.
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:102)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:114)
	at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:109)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:233)
	at kotlinx.serialization.json.internal.JsonStreamsKt.encodeByWriter(JsonStreams.kt:28)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:81)
```

### Can you reproduce the bug?

Always

### Version

kotlin SDK 1.10.2

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

windows 10

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by helmysaeed** [comment]
Exception in thread "main" kotlinx.serialization.SerializationException: Class 'RealmResultsImpl' is not registered for polymorphic serialization in the scope of 'RealmResults'.
To be registered automatically, class 'RealmResultsImpl' has to be '@Serializable', and the base class 'RealmResults' has to be sealed and '@Serializable'.

**Comment by clementetb** [comment]
`RealmList` does not have an embedded kserializer defined and it requires manual registration. 

[RealmListKSerializer](https://www.mongodb.com/docs/realm-sdks/kotlin/latest/library-base/io.realm.kotlin.serializers/-realm-list-k-serializer/index.html) is a serializer for both managed and unmanaged lists. The documentation shows different ways of registration.

**Comment by helmysaeed** [comment]
> `RealmList` does not have an embedded kserializer defined and it requires manual registration.
> 
> [RealmListKSerializer](https://www.mongodb.com/docs/realm-sdks/kotlin/latest/library-base/io.realm.kotlin.serializers/-realm-list-k-serializer/index.html) is a serializer for both managed and unmanaged lists. The documentation shows different ways of registration.

yes  I registered all types inside the model class  with 

@file:UseSerializers(
    RealmListKSerializer::class,
    RealmInstantKSerializer::class,
    RealmSetKSerializer::class,
    RealmAnyKSerializer::class,
    RealmDictionaryKSerializer::class,
    RealmInstantKSerializer::class,
    RealmAnyKSerializer::class,
    RealmUUIDKSerializer::class,
    MutableRealmIntKSerializer::class,
   MutableRealmIntKSerializer::class,
   

    RealmInstantKSerializer::class
)

**Comment by helmysaeed** [comment]
Is there any real  example of one-to-many relationship  and realmlist serialization

**Comment by clementetb** [comment]
We don't have any examples, but we have a bunch of tests [here](https://github.com/realm/realm-kotlin/blob/b6cea0f67243e4efeaeb5ddc3efe715aaf84d7d8/packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/SerializationTests.kt#L4). 

If you have any issues with any of the serializers available in the SDK, share some samples or details and we will be happy to assist.

**Comment by helmysaeed** [comment]
> We don't have any examples, but we have a bunch of tests [here](https://github.com/realm/realm-kotlin/blob/b6cea0f67243e4efeaeb5ddc3efe715aaf84d7d8/packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/SerializationTests.kt#L4).
> 
> If you have any issues with any of the serializers available in the SDK, share some samples or details and we will be happy to assist.



@file:UseSerializers(
    RealmListKSerializer::class,
    RealmInstantKSerializer::class,
    RealmSetKSerializer::class,
    RealmAnyKSerializer::class,
    RealmDictionaryKSerializer::class,
    RealmInstantKSerializer::class,
    RealmAnyKSerializer::class,
    RealmUUIDKSerializer::class,
    MutableRealmIntKSerializer::class,
    MutableRealmIntKSerializer::class,


    RealmInstantKSerializer::class
)


package com.example.common.Data

import io.realm.kotlin.ext.realmListOf
import io.realm.kotlin.serializers.*
import io.realm.kotlin.types.RealmObject
import kotlinx.serialization.UseSerializers
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.mongodb.kbson.ObjectId


class  Employ : RealmObject

{
    var id:ObjectId=ObjectId()
     var  name =""


}


class  EmploySalary : RealmObject

{
    var id:ObjectId=ObjectId()
    var  salary :Double=0.0
    var employ:Employ= Employ()


}


fun mainTest() {


    var emp =  Employ()
    emp.name="emp1"

    var salary = EmploySalary()

    salary.salary=1000.0
     salary.employ=emp

    var emp2= Employ()

    emp2.name="emp2"

    var salary2= EmploySalary()
    salary2.salary=2000.0
    salary2.employ=emp2

    var employList = realmListOf<EmploySalary>()

    employList.add(salary)
    employList.add(salary2)

 println( Json.encodeToString( employList))

}

**Comment by clementetb** [comment]
I see the issue. The `@file:UseSerializers` annotation works for registering the serializer for any `RealmList` property in the models defined in the file, then when you serialize that model KSerializer knows how to serialize such property.

This annotation would not register the serializer on `RealmList`s defined in a code block, like in your case. In this case you will have to manually pass the serializer to the `Json.encodeToString`:

```kotlin
println(Json.encodeToString(RealmListKSerializer, employList))
```

**Comment by helmysaeed** [comment]
> I see the issue. The `@file:UseSerializers` annotation works for registering the serializer for any `RealmList` property in the models defined in the file, then when you serialize that model KSerializer knows how to serialize such property.
> 
> This annotation would not register the serializer on `RealmList`s defined in a code block, like in your case. In this case you will have to manually pass the serializer to the `Json.encodeToString`:
> 
> ```kotlin
> println(Json.encodeToString(RealmListKSerializer, employList))
> ```
Classifier 'RealmListKSerializer' does not have a companion object, and thus must be initialized here

**Comment by clementetb** [comment]
Yes, you have to initialize the `RealmListKSerializer`. In your case:

```
println(Json.encodeToString(RealmListKSerializer(EmploySalary.serializer()), employList))
```

Note, that you have to annotate `EmploySalary` as `@Serializable`, or it will not be able to pull its serializer.

**Comment by helmysaeed** [comment]
thank you a lot @cmelchior  it works perfectly
