### ISSUE TITLE
No implementation found for void io.realm.kotlin.internal.interop.realmcJNI.set_log_callback

### ISSUE THREAD

**Issue by ronjunevaldoz** [realm/realm-kotlin#1508]
### How frequently does the bug occur?

Always

### Description

Trying to setup using the latest Kotlin compose multiplatform `1.5.0`. The dependency is working properly but when accessing the realm it gives an error.

```kotlin
val realm by lazy {
    val config = RealmConfiguration.create(setOf(Task::class))
    Realm.open(config)
}
```

### Stacktrace & log output

```shell
`No implementation found for void io.realm.kotlin.internal.interop.realmcJNI.set_log_callback(int, java.lang.Object) (tried Java_io_realm_kotlin_internal_interop_realmcJNI_set_1log_1callback and Java_io_realm_kotlin_internal_interop_realmcJNI_set_1log_1callback__ILjava_lang_Object_2)`
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Setup the realm using kotlin compose multiplatform template `1.5.0` https://github.com/JetBrains/compose-multiplatform-template#readme
 
Additional changes made: 

```kotlin
android {
    compileSdk = (findProperty("android.compileSdk") as String).toInt()
    namespace = "com.myapplication.common"

    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    sourceSets["main"].res.srcDirs("src/androidMain/res")
    sourceSets["main"].resources.srcDirs("src/commonMain/resources")
    defaultConfig {
        minSdk = (findProperty("android.minSdk") as String).toInt()
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        jvmToolchain(17)
    }
}



// work around realm
project.afterEvaluate {
    kotlin.targets .all {
         compilations.all {
            (kotlinOptions as? org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptions)?.jvmTarget = "17"
        }
    }
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor(0, "seconds")
}
```

### Version

1.11.1

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Windows 11

### Build environment

Android Studio version: Android Studio Giraffe | 2022.3.1 Patch 1
Android Build Tools version: 8.0.2
Gradle version: 8.2.1

**Comment by cmelchior** [comment]
It looks like the native code doesn't contain that particular method. It was added in 1.8.0, so perhaps you are somehow loading an older version of the native code.

Two questions:
- Are the plugin and library dependency using the same version?
- Are you launching your app with `java.libraries.path` defined? If yes, there is a chance it is loading an older version of our `.so` file as we will then use that instead of the one packaged in our dependency. See https://github.com/realm/realm-kotlin/pull/1116 for more details.

**Comment by ronjunevaldoz** [comment]
1. I was using `1.11.1` for both plugin and library
`id("io.realm.kotlin").version(1.11.1)`
`io.realm.kotlin:library-base:1.11.1`
2. No I'm not overriding any `java.libraries.path`

**Comment by cmelchior** [comment]
I just tried to run https://github.com/realm/realm-kotlin-samples/tree/main/JVMConsole with Realm 1.11.1 on Windows and it loads fine.

So I still suspect it is a problem somewhere in your setup. Have you tried to reproduce it on multiple machines? (if available)

If you can reproduce in a small sample project, can you share that?

**Comment by ronjunevaldoz** [comment]
My bad @cmelchior you're right, since I've added opencv custom project as implementation instead of api, it affects the realm dependencies.

**Comment by timonmw** [comment]
i have the same problem but i don't have any provider in my project. Did you solve it by just removing the Provider?

**Comment by langsmith** [comment]
I'm using `io.realm.kotlin:library-base:1.11.1`, and like @ronjunevaldoz , had the `InitializationProvider` in my manifest. Removing the `InitializationProvider` got the Realm `set_log_callback`  💥 to go away. **However**, I needed the `InitializationProvider` to get WorkManager working with Hilt 😕

**Comment by langsmith** [comment]
https://developer.android.com/guide/background/persistent/configuration/custom-configuration#remove-default

https://stackoverflow.com/questions/59710362/workmanager-should-we-remove-the-default-initializer-when-we-use-both-default

https://stackoverflow.com/questions/63951589/hiltworkerfactory-configure-workmanagerinitializer-at-appstartup

**Comment by timonmw** [comment]
`
        val appInitializer = AppInitializer.getInstance(this)
        appInitializer.initializeComponent(RealmInitializer::class.java)
`
This solved the Problem for me without removing the InitializationProvider

**Comment by langsmith** [comment]
> ```
>         val appInitializer = AppInitializer.getInstance(this)
>         appInitializer.initializeComponent(RealmInitializer::class.java)
> ```
> 
> This solved the Problem for me without removing the InitializationProvider

@timonmw , where did you run that code?

**Comment by timonmw** [comment]
@langsmith I put it in the onCreate of the Application

**Comment by kenhuang** [comment]
any suggestion how we can apply similar changes to a react-native Android project? seems facing a similar issue when we upgraded to react-native 0.72, our project use both `realm-js` and `realm-kotlin`.

Getting the following error on `MainApplication.java` and followed this [installation](https://github.com/realm/realm-kotlin#installation) guide.
```
 Getting compile error:  MainApplication.java:67: error: <identifier> expected appInitializer.initializeComponent(RealmInitializer::class.java);
```

finding similar changes on `AndroidManifest.xml` after react-native 0.72 upgrade:
```
 <provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="com.example.androidx-startup"
            android:exported="false" >
...
```
