### ISSUE TITLE
Slow queries with embedded objects when compared to Realm Java

### ISSUE THREAD

**Issue by kanytu** [realm/realm-kotlin#1529]
### How frequently does the bug occur?

Always

### Description

During our migration from Realm Java to Realm Kotlin in our Android project, a severe performance drop in some of our queries was observed.

For reference, we have a Realm Object with the following schema:

```
class BookRealm {
   @PrimaryKey var idRealm: String = EMPTY_STRING,
    var metas: RealmList<MetadataRealm> = realmListOf(),
}
```

The `MetadataRealm` is has the following schema:

```
class MetadataRealm(
    var key: String = EMPTY_STRING,
    var values: RealmList<String?> = realmListOf()
) : EmbeddedRealmObject
```

For our test, we have 100 BookRealm objects. On average, each one of them has 10 MetadataRealm, which all have a single object in `values `.

Fetching all `BookRealm` objects and accessing their `metas` objects is on average, 5 times slower in Kotlin.

### Can you reproduce the bug?

Always

### Version

1.10.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

Android 13

**Comment by cmelchior** [comment]
Hi @kanytu Can you share how you are measuring that?

**Comment by kanytu** [comment]
Sure thing.

We have two branches or our application. They share the same schema. One has Realm Java (v10.16.1) and the other has Realm Kotlin (v1.10.0).

Transition between both branches when installing one APK over the other is seamless, however, some of our queries are taking longer.

We are evaluating that with both [measureTimeMillis](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.system/measure-time-millis.html) and Android Profiler.

The code of the query is very simple. We are querying all objects of a given class and applying a transformation to them.
In realm Kotlin we are achieving that with `find(transform)` extension function. The transform method creates a new class with the mapped version of `metas`.

For the same code (transform and query format) the results are way different.

Upon inspection, we came to the conclusion that this was caused by a regression in performance when accessing values from these type of embedded objects:

<img width="579" alt="image" src="https://github.com/realm/realm-kotlin/assets/560921/2ced368d-35c3-4c36-9334-3992fccd5ae6">

The operation of retrieving the list takes a long time, way longer than before (Realm Java)

Thanks,
Pedro O.

**Comment by cmelchior** [comment]
Hi @kanytu Thank you for that description, but I was probably not clear enough. Do you mind posting the code for both Java and Kotlin? Just so we are 100% sure we know what is going on.

**Comment by kanytu** [comment]
The code we are using for Realm-java:

```
val result = realmInstance.where(BookRealm::class.java).findAll()
val newObject = result.map { Book(it.metas.mapValues { value -> value.value.toList() }) }
```

In Kotlin:

```
val result = realmInstance.query(BookRealm::class).find { results ->
    results.map { result -> NewObject(result.metas.mapValues { value -> value.value.toList() }) }
}
```

**Comment by cmelchior** [comment]
Hi @kanytu 

I tried to reproduce your numbers, but I'm not able to replicate it. I pushed my benchmark code here: https://github.com/realm/realm-kotlin/commit/81266e420437ff6a3453269fecbddde28084557e. Maybe you can see a difference compared to yours.

This were the numbers I was getting:

```
Starting Java test
Max: 908
Max: 908
Min: 88
Average: 143.28
Median: 100

Starting Kotlin test
Max: 542
Min: 118
Average: 160.62
Median: 136

Starting Java test
Max: 1011
Min: 82
Average: 128.7
Median: 94

Starting Kotlin test
Max: 499
Min: 115
Average: 147.09
Median: 130
```

Which does show that Kotlin is slightly slower. But not 5x, more like 10-15% which is what we would expect. 

Currently, the code path in Kotlin is a bit more generic than in Java, which does have a slightly higher overhead, but it makes maintaining and changing the code much easier. We have some ideas on how to improve it, but it isn't on the near-term roadmap. That said, if you are seeing 5x increases, that is something we would want to investigate.

Can you potentially try to run the code in my branch and see what kind of numbers you are getting? At least that will tell us if my benchmark is doing something your code is not, which will help us narrow down the problem.

**Comment by kanytu** [comment]
We are not using `copyFromRealm` but rather creating a new object with the values.

**Comment by cmelchior** [comment]
Hi @kanytu, Yes, `copyFromRealm` is basically just a quick way to do what you do, read properties into a new object, so it should behave the same as your code.
