### ISSUE TITLE
SIGSEGV: register_results_notification_cb(realm_results*, _jobject*)

### ISSUE THREAD

**Issue by Shabinder** [realm/realm-kotlin#1577]
### How frequently does the bug occur?
Sometimes

### Description
We are seeing following crashes reported on our Android App (distributed via playstore)

[split_config.arm64_v8a.apk!librealmc.so] register_results_notification_cb(realm_results_, _jobject_)

Only Samsung devices are inflicted like:

* samsung m32
* samsung b5q
* samsung beyond2
* samsung a32x

### Stacktrace & log output
```shell
[split_config.arm64_v8a.apk!librealmc.so] register_results_notification_cb(realm_results*, _jobject*)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 10238 >>> com.subconscious.thrive <<<

backtrace:
  #00  pc 0x0000000000460ba0  /apex/com.android.art/lib64/libart.so (art::FindMethodJNI(art::ScopedObjectAccess const&, _jclass*, char const*, char const*, bool)+80)
  #01  pc 0x000000000046cf78  /apex/com.android.art/lib64/libart.so (art::JNI<false>::GetMethodID(_JNIEnv*, _jclass*, char const*, char const*)+616)
  #02  pc 0x00000000002fc338  /data/app/~~RmIHjfJYizSUN8-Lh1EESw==/com.subconscious.thrive-NBb_Gunk0DIJ7S4GEKb0bg==/split_config.arm64_v8a.apk!librealmc.so (register_results_notification_cb(realm_results*, _jobject*)+380) (BuildId: 533e53c62871f9d2818ed137fd0c02c6241c7609)
  #03  pc 0x00000000002f9b34  /data/app/~~RmIHjfJYizSUN8-Lh1EESw==/com.subconscious.thrive-NBb_Gunk0DIJ7S4GEKb0bg==/split_config.arm64_v8a.apk!librealmc.so (Java_io_realm_kotlin_internal_interop_realmcJNI_register_1results_1notification_1cb+24) (BuildId: 533e53c62871f9d2818ed137fd0c02c6241c7609)
  #04  pc 0x0000000000394cc4  /data/app/~~RmIHjfJYizSUN8-Lh1EESw==/com.subconscious.thrive-NBb_Gunk0DIJ7S4GEKb0bg==/oat/arm64/base.odex (art_jni_trampoline+116)
  #05  pc 0x00000000010a6004  /data/app/~~RmIHjfJYizSUN8-Lh1EESw==/com.subconscious.thrive-NBb_Gunk0DIJ7S4GEKb0bg==/oat/arm64/base.odex (io.realm.kotlin.internal.RealmResultsImpl.q+356)
  #06  pc 0x000000000116c3a0  /data/app/~~RmIHjfJYizSUN8-Lh1EESw==/com.subconscious.thrive-NBb_Gunk0DIJ7S4GEKb0bg==/oat/arm64/base.odex (io.realm.kotlin.internal.SuspendableNotifier$registerObserver$1$1.invokeSuspend+1072)
  #07  pc 0x00000000010072d4  /data/app/~~RmIHjfJYizSUN8-Lh1EESw==/com.subconscious.thrive-NBb_Gunk0DIJ7S4GEKb0bg==/oat/arm64/base.odex (kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith+180)
  #08  pc 0x000000000130b3dc  /data/app/~~RmIHjfJYizSUN8-Lh1EESw==/com.subconscious.thrive-NBb_Gunk0DIJ7S4GEKb0bg==/oat/arm64/base.odex (kotlinx.coroutines.DispatchedTask.run+1052)
  #09  pc 0x000000000037b5ec  /apex/com.android.art/javalib/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+988)
  #10  pc 0x0000000000374e14  /apex/com.android.art/javalib/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+68)
  #11  pc 0x00000000001bf2ec  /apex/com.android.art/javalib/arm64/boot.oat (java.lang.Thread.run+76)
  #12  pc 0x0000000000218964  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548)
  #13  pc 0x00000000002851f0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+184)
  #14  pc 0x0000000000628a24  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460)
  #15  pc 0x0000000000678488  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1184)
  #16  pc 0x00000000000b4b38  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264)
  #17  pc 0x0000000000052c60  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

### Can you reproduce the bug?
No

### Version
1.10.0

### What Atlas App Services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
Android 13 and 12

### Build environment
Android Studio version: Iguana
Gradle version: 8.0.2

**Comment by rorbech** [comment]
Hi @Shabinder. Seems like there is an issue looking up a JNI method from out native code. It looks like you have enabled abi-splitting. I am not fully on top of how this works, but could be that the JVM symbols are not included because they are not referenced from JVM code, so an possible quick fix could be to disable splitting. 

Might be that there are other issues in play so maybe try to elaborate on the details about your project: 
- Size
- ABIs
- Proguard/R8
Or any other non-default project configurations.

**Comment by Shabinder** [comment]
- Proguard rules are pretty standard ones.
if they weren't, and would be the cause, then release builds would always consistently crash and not only sometimes.

- ABI splitting: we could turn this off, but that would result in a significant spike in the size of the app which is unwarranted.

**Comment by rorbech** [comment]
We specifically provide proguard-consumer files to preserve the classes that we require to keep around. I don't know how the abi-splitting is done and if you can get it to honor these definitions. Are you able to provoke this with local testing of split test apps? And/or do you have any indications of if the apps are somehow sideloaded with nonstandard post processing of the apks?

**Comment by Shabinder** [comment]
- proguard-consumer files are being honored.
 
 

> And/or do you have any indications of if the apps are somehow sideloaded with nonstandard post processing of the apks?

 
 I suspect this only as well, since not reproducible and not all are affected, there is no clear indication if above is the case, is there something I can do to have certainity on that ?

**Comment by rorbech** [comment]
To my knowledge the only way is to access the information through the [`PackageManager` APIs](https://developer.android.com/reference/android/content/pm/InstallSourceInfo). It has varied a bit throughout Android versions. Maybe you can report it as a custom key along with the crashes in Android vitals/crashlytics.

**Comment by Shabinder** [comment]
We shall see what we can do, also pointing out these crashes don't get reported in crashlytics and are reported in Play Console Android Vitals, I am suspecting because these are ABRT signals from Native Code.

**Comment by rorbech** [comment]
Revisiting this, it came up that we have seen some similar for callbacks on non-attached threads. I can't really see a way to achieve this, but the JNI references should anyway be resolved and cached on library load time. Could still be that there is an issue with on the splits (or repackaging), but would be interesting to see if the issue persists after #1598 is merged.
