### ISSUE TITLE
Float value changes after writing to realm even for integer part of the complete number

### ISSUE THREAD

**Issue by gauravbordoloi** [realm/realm-kotlin#1589]
### How frequently does the bug occur?
Always

### Description
The following issue was raised for realm javascript (https://github.com/realm/realm-js/issues/6293) but it was also happening for realm-kotlin as we faced the same issue.

Float value changes after writing to realm even for integer part of the complete number

    import Realm from "realm"
    
    class TData extends Realm.Object {
        static schema = {
            name: "CategoryModel",
            properties: {
                b: "string",
                a: "double",
                c: "float",
            },
            primaryKey: 'b',
        }
    }
    
    const db = {
        //path: DB_PATH,
        schema: [TData]
    }
    
    let realm = await Realm.open(db);
    
    let p = `${Date.now()}`
    
    let v = 1628899821
    
    realm.write(() => {
        realm.create(TData, { a: v, c: v, b: p })
    })
    
    console.log(realm.objectForPrimaryKey(TData, p).toJSON())![image](https://github.com/realm/realm-kotlin/assets/23193185/05c55cbd-f731-496f-8385-c614bc88f82d)

### Can you reproduce the bug?
  * select --

### Version
1.12.0

### What Atlas App Services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
Android

### Build environment
Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by nirinchev** [comment]
As mentioned in the JS answer, the issue is related to the fact you're using a 32-bit float to represent ~31-bit integer value. This is not possible and you need to use a larger data structure.
