### ISSUE TITLE
Flaky test: write_voidBlockIsNotTracked[macos] – io.realm.kotlin.test.common.VersionTrackingTests

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#1596]
`
kotlin.AssertionError: VersionInfo(main=VersionData(current=null, active=[]), notifier=VersionData(current=VersionId(version=3), active=[]), writer=VersionData(current=VersionId(version=3), active=[VersionId(version=3)])). Expected <2>, actual <1>.
`

From https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-1595/1/tests

**Comment by rorbech** [comment]
Also seen in https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-1587/9/tests/

**Comment by cmelchior** [comment]
We are pretty sure this is fixed by: https://github.com/realm/realm-kotlin/pull/1599
Due to timing issues, the GC might have already cleared the first version.
