### ISSUE TITLE
Gradl Task :androidApp:stripDebugDebugSymbols

### ISSUE THREAD

**Issue by Morons** [realm/realm-kotlin#1609]
### How frequently does the bug occur?

Always

### Description

Getting this from Android Project Build
```
`Task :androidApp:stripDebugDebugSymbols`
Unable to strip the following libraries, packaging them as they are: librealmc.so.
```

### Stacktrace & log output

```shell
> Task :androidApp:stripDebugDebugSymbols
Unable to strip the following libraries, packaging them as they are: librealmc.so.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

io.realm.kotlin:library-base v 1.13.0

### Version

compileSdk = 34

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Windows 11.0

### Build environment

Android Studio Hedgehog | 2023.1.1
Build #AI-231.9392.1.2311.11076708, built on November 9, 2023
Java Runtime version: 17.0.7+0-b2043.56-10550314 amd64
```
implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.21")
implementation("com.android.tools.build:gradle:8.2.0")
```
`gradle-8.2-all.zip`

**Comment by cmelchior** [comment]
This is not a bug, it is intentional that we strip the libraries before shipping them to keep the size down. It is correct that the Android Gradle Plugin will report this in the logs, but it should be harmless and can be ignored.
