### ISSUE TITLE
Find a good way to unit test Coroutines in Common code

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#164]
On the JVM there is `runBlocking { }` which is super helpful for writing coroutines unit tests. Unfortunately, this isn't available in common code. This issue https://github.com/Kotlin/kotlinx.coroutines/issues/1996 have a few proposed work-arounds but my immediate attempt at adopting it failed.

We need to investigate what the best way is for writing unit tests involving coroutines.

**Comment by JavierSegoviaCordoba** [comment]
`runBlocking` exists in all targets except JS, so you can create an expect/actual in common code using it

**Comment by cmelchior** [comment]
Ah cool. Thanks for the info. That will be useful 👍

**Comment by rorbech** [comment]
As pointed out `runBlocking` is already available for non-JS platforms which suffices for now. I added an internal platform abstract method to allow us to use it in common code internally in #222 https://github.com/realm/realm-kotlin/pull/222/files#diff-d6c37b5382141c6c0dbc51221e4a16e1e515739525042068f49854089acc1c05R26
