### ISSUE TITLE
Potential problem with Platform networking 

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#1641]
This seems to be the root cause of some of the problems we are seeing with our Sync Tests on Jenkins.

It can be reproduced in the following way:

1. Checkout `[cm/fix-progress-test](https://github.com/realm/realm-kotlin/tree/cm/fix-progress-test), from https://github.com/realm/realm-kotlin/pull/1633

2. Modify AsymmetricSyncTests setup to enable platform networking:

```
    @BeforeTest
    fun setup() {
        app = TestApp(this::class.simpleName, appName = TEST_APP_FLEX, builder = { builder ->
            builder.usePlatformNetworking(false)
            builder
        })
        val (email, password) = TestHelper.randomEmail() to "password1234"
        val user = runBlocking {
            app.createUserAndLogIn(email, password)
        }
        config = SyncConfiguration.Builder(
            user,
            schema = FLEXIBLE_SYNC_SCHEMA
        ).errorHandler { session, error ->
            println(error)
        }.initialSubscriptions {
            it.query<DeviceParent>().subscribe()
        }.build()
        realm = Realm.open(config)
    }
```

3. Start the local test server using `./start_local_test_server.sh`

4. Run `AsymmetricSyncTests.asymmetricSchema()` from inside Android Studio.

5. This will now fail with a timeout for `uploadAllLocalChanges()`.

6. Rerunning the test will now succeed. Rerunning step 3 and 4 with platform networking disabled will work for this test.

7. Running the `AsymmetricSyncTest.insert()` from a fresh server with Platform networking disabled will instead result in an `AutoClientResetFailed(1028)` error being thrown. More details are reported here: https://github.com/realm/realm-core/pull/7291#pullrequestreview-1844241258

So right now it is a bit unclear if this is a problem with the server, the Sync Client, Client Reset, Platform Networking or all of the above. But something is clearly not working as intended

**Comment by nirinchev** [comment]
This was fixed in https://github.com/realm/realm-kotlin/pull/1645.
