### ISSUE TITLE
Examples on the website contains Swift code instead of Kotlin

### ISSUE THREAD

**Issue by xVemu** [realm/realm-kotlin#1655]
### Description

In the `What does storing and querying data in Realm look like?` section of [Realm Kotlin](https://realm.io/realm-kotlin/) page, we can see Swift code instead of Kotlin.

**Comment by kneth** [comment]
@xVemu realm.io is slowly phased out, and we recommend that you take a look at https://www.mongodb.com/docs/realm/sdk/kotlin/quick-start/ instead.
