### ISSUE TITLE
Getting "[Core] Testing/debugging feature 'one connection per session' enabled - never do this in production" warnings

### ISSUE THREAD

**Issue by benoitletondor** [realm/realm-kotlin#1687]
### How frequently does the bug occur?

Always

### Description

I'm seeing this log in an app in production:

```
[Core] Testing/debugging feature 'one connection per session' enabled - never do this in production
```

Nothing is enabled regarding a one connection per session mode, not even sure what this is.

### Stacktrace & log output

```shell
[Core] Testing/debugging feature 'one connection per session' enabled - never do this in production
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Using flexible sync on an Atlas app

### Version

1.14.0

### What Atlas App Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

Android, not related to a specific version

### Build environment

Android Studio version: Android Studio Iguana | 2023.2.1
Android Build Tools version: 8.3.0
Gradle version: 8.6

**Comment by kneth** [comment]
@benoitletondor The log message is a friendly reminder to  [enable multiplexing](https://www.mongodb.com/docs/realm-sdks/kotlin/latest/library-sync/io.realm.kotlin.mongodb/-app-configuration/enable-session-multiplexing.html?query=abstract%20val%20enableSessionMultiplexing:%20Boolean).

**Comment by benoitletondor** [comment]
Thanks a lot @kneth , will update my implementation.

Note that as friendly as this reminder is it's not really clear to me, but not a big deal since I got your explanation.

Thanks again
