### ISSUE TITLE
Issue 1688 (No scheduler for platform) still exists in 1.11.1 version of Realm

### ISSUE THREAD

**Issue by darrinps** [realm/realm-kotlin#1693]
### How frequently does the bug occur?

Always

### Description

Please refer to https://github.com/realm/realm-kotlin/issues/1688 for a full overview.

I set the version to 1.11.1 as it is supposed to have this issue resolved:

<img width="424" alt="image" src="https://github.com/realm/realm-kotlin/assets/1413196/404fe94c-5621-47cc-941d-c0b8f3ec5c4b">

### Stacktrace & log output

```shell
The only thing I could see was:

scheduler.cpp:134: [realm-core-13.19.0] No built-in scheduler implementation for this platform.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Set the realm version to 1.11.1 then execute the code:

`    
     val configuration = RealmConfiguration.create(schema = setOf(PelletLot::class))
     val realm = Realm.open(configuration)   //<-- Will error here 
`  

### Version

1.11.1

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Kotlin 1.9.22 Android 34 for a Desktop app running on Windows 11

### Build environment

Android Studio version: ... 2023.2.1 (Iguana)
Android Build Tools version: ...35-rc1
Gradle version: ...8.5

**Comment by rorbech** [comment]
Hi @darrinps. This should have been fixed. Did you also update the `library-base` dependency to `1.11.1`? Or maybe even try with latests `1.14.1`.

**Comment by darrinps** [comment]
That was the problem. The plugin was updated to 1.11.1, but the library
base dependency was still sitting at 1.11.0.

I'll close it now. Thanks!
