### ISSUE TITLE
Gradle sync issues in Kotlin Multiplatform project

### ISSUE THREAD

**Issue by joreilly** [realm/realm-kotlin#170]
Hi, I'm trying out the new Kotlin Multiplatform support but running in to a variety of gradle sync issues.  I've tried the sample included and that seems to work.  Are there known issues around this or any particular fixes planned?

Specifically I've created a branch of https://github.com/joreilly/PeopleInSpace and was starting initially to add in realm plugin/dependencies to gradle.  I tried adding classpath for plugin in same way as other plugins (along with `repositories` update) but that seems to trigger ton of errors when syncing `build.gradle.kts` in kmp module.  I also tried approach in sample but also get errors with that.

**Comment by nhachicha** [comment]
Hi @joreilly Thanks for trying this out, currently we're not publishing for `JVM` and `JS` targets did you try disabling these and build? 
At some point, I tried adding Realm into your SpaceX KMM app and it did work.

**Comment by joreilly** [comment]
Ah, that could likely be the issue.  Are there plans in near future to support those platforms?

**Comment by nhachicha** [comment]
Yes JVM is planned https://github.com/realm/realm-kotlin/issues/62 we're not using a lot of Android API (besides the Context for some file operations and the Looper to deliver notification). JS is more challenging since we're relying on native C++ engine using libraries and system calls that are not available in JS/Web assembly

**Comment by joreilly** [comment]
I just tried disabling those targets but still running in to same issue (in https://github.com/joreilly/PeopleInSpace).  Will try in a different project later.

**Comment by joreilly** [comment]
I think I must have messed up something on first attempt to add to PeopleInSpace.....started again with it and having more success now getting gradle setup working.

**Comment by joreilly** [comment]
@nhachicha a little outside scope of this issue.....but is there way right now, when using realm in kmm code, to get result as a flow?

**Comment by ianpward** [comment]
@joreilly I believe you should should be able to use the `toFlow()` extension function - https://docs.mongodb.com/realm-sdks/kotlin/10.0.0/kotlin-extensions/io.realm.kotlin/io.realm.-realm-results/to-flow.html

**Comment by joreilly** [comment]
I saw that in one of the examples but didn't seem to be available....perhaps i need to pull in another dependency.  I have following for example as my starting point.  I saw the examples used `where` here but that didn't seem to be available either.

```
realm.objects<AssignmentDb>()
```

**Comment by cmelchior** [comment]
@joreilly Not right now, sorry. This is one of the things we want to add as soon as we can, but it hinges on a rather big architectural rewrite.

Right now the exposed API mirrors what we have in Realm Java with live, thread-confined objects, but we are changing it to expose immutable objects instead that can be used automatically across all threads. We have written down our thoughts here: https://docs.google.com/document/d/1bGfjbKLD6DSBpTiVwyorSBcMqkUQWedAmmS_VAhL8QU/edit#heading=h.fzlh39twuifc

And we did a sprint last week prototyping how it might look here: https://github.com/realm/realm-kotlin/pull/163/files#diff-6dad56c6fe2f27e41d6f3103692e5a70a560f31413d9a270c107fb3b9f9f6c44R52

**Comment by joreilly** [comment]
I've pushed changes I've made so far to following branch https://github.com/joreilly/PeopleInSpace/tree/realm

The main realm related changes I've made are in https://github.com/joreilly/PeopleInSpace/blob/realm/common/src/commonMain/kotlin/com/surrus/common/repository/PeopleInSpaceRepository.kt

As first attempt/hack I updated following method as follows (but obviously that won't allow updates to data to be reflected):

```
    fun fetchPeopleAsFlow(): Flow<List<Assignment>> {
        val allPeople = realm.objects<AssignmentDb>().toList().map {
            Assignment(name = it.name, craft = it.craft)
        }
        return flowOf(allPeople)
    }
```

**Comment by joreilly** [comment]
I see that there's an `observe()` method I can call.....should I be able to get updates using that (and then `emit()` to a flow for now)?

**Comment by cmelchior** [comment]
In theory yes, it is possible to wrap that in a `callbackFlow` like here: https://github.com/realm/realm-kotlin/pull/163/files#diff-98286e997dda9b7d29cb762e21b0fcde07d1bc26937eeffdf97b60ca4f0cc6bfR46 (addChangeListener is the observe method renamed)... but since it is emitting Live objects you might quickly run into IllegalThreadExceptions.

**Comment by joreilly** [comment]
I tried following as test and seems to work (on both Android and iOS)

```
    fun fetchPeopleAsFlow(): Flow<List<Assignment>> {
        return callbackFlow {
            val callback = Callback<RealmResults<AssignmentDb>> {
                val allPeople = it.toList().map {
                    Assignment(name = it.name, craft = it.craft)
                }
                offer(allPeople)
            }
            realm.objects<AssignmentDb>().observe(callback)

            awaitClose {
            }
        }
    }
```

**Comment by nhachicha** [comment]
@joreilly great to hear that you managed to figure it out. Do we have your permission to fork and copy your example to be part of our `samples`project

**Comment by joreilly** [comment]
@nhachicha yeah, no problem at all.....this particular project is by definition pretty minimal and also the Realm code that's there right now is just first cut so probably better way of doing some of what I've added....obviously feel free to modify as needed.  BTW the changes are still in the `realm` branch.....I think I'm going to keep `main` branch as is for this project and add Realm to another KMM project I created recently that hasn't got persistence implemented yet.

**Comment by joreilly** [comment]
just fyi that I've also added use of Realm to another KMP project (https://github.com/joreilly/FantasyPremierLeague/tree/realm).  This has at least a somewhat less trivial data model (compared to PeopleInSpace).  Again this is in a separate branch (`realm`) for now....most of these projects also have Compose for Desktop so lack of JVM support will prevent merging to `main` for now...

```
class TeamDb: RealmObject {
    var id: Int = 0
    var index: Int = 0
    var name: String = ""
    var code: Int = 0
}

class PlayerDb: RealmObject {
    var id: Int = 0
    var firstName: String = ""
    var secondName: String = ""
    var code: Int = 0
    var teamCode: Int = 0
    var totalPoints: Int = 0
    var nowCost: Int = 0
    var goalsScored: Int = 0
    var assists: Int = 0
    var team: TeamDb? = null
}

class FixtureDb: RealmObject {
    var id: Int = 0
    var kickoffTime: String? = ""
    var homeTeam: TeamDb? = null
    var awayTeam: TeamDb? = null
    var homeTeamScore: Int = 0
    var awayTeamScore: Int = 0
}
```

**Comment by joreilly** [comment]
Feel free to close this btw 😃
