### ISSUE TITLE
Could not find com.uphyca:stetho_realm:2.3.0

### ISSUE THREAD

**Issue by anil2546** [realm/realm-kotlin#172]
Build is failing due to could not find com.uphyca:stetho_realm:2.2.2.

Added 
in app level 
maven { url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo' }
maven { url 'https://github.com/WickeDev/stetho-realm/raw/master/maven-repo' }

in build.gradle 
implementation 'com.uphyca:stetho_realm:2.2.2'

**Comment by cmelchior** [comment]
Hi @anil2546 
Unfortunately that is outside our control, you will need to raise the issue at https://github.com/uPhyca/stetho-realm/issues
