### ISSUE TITLE
Compiler plugin errors should provide more context

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#173]
Annotation processor errors in Realm Java made it possible to link to the syntax element that was causing the error. This was super helpful in terms of tracking down where the problem is.

I'm not sure if something similar is possible with the Kotlin Compiler, but just outputting something like:

![image](https://user-images.githubusercontent.com/406066/115857623-3041c680-a42e-11eb-8cc6-0e30e1ee7fbd.png)

Is not particularly helpful... As a minimum, we should identify the file, method, and ideally line that is causing the issue or expression so you can easily find it.

**Comment by rorbech** [comment]
We should also provide sane error descriptions. Defining a property as `val` will just yield 
```
Caused by: java.lang.ClassCastException: io.realm.entities.schema.SchemaVariations$Companion$$realm$fields$20 cannot be cast to kotlin.reflect.KMutableProperty1
```
instead of explaining that it must be `var`.
