### ISSUE TITLE
Could the realm-kotlin community please support the same minimum macOS version as realm-core?

### ISSUE THREAD

**Issue by guiyanakuang** [realm/realm-kotlin#1742]
### Problem

In version 1.16.0

When using the command `otool -l librealmc.dylib | grep minos`, the output indicates:

`minos 12.7`

However, it seems that the minimum version supported by realm-core is macOS 10.13, as detailed in the realm-core GitHub repository:
https://github.com/realm/realm-core/blob/889d26dc735a6d2e8c5bfd8b2b380f3f0c99dba3/Package.swift#L355-L360

Supporting a lower version would accommodate a broader user base.

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by nirinchev** [comment]
This is not something we're prioritizing at this point.
