### ISSUE TITLE
jvmTarget replaced

### ISSUE THREAD

**Issue by Efimj** [realm/realm-kotlin#1766]
### How frequently does the bug occur?

Always

### Description

Recently i updated my project to Java 17 and discovered kapt errors. After searching for errors I found this:
```
private fun updateKotlinOption(target: KotlinTarget) {
        target.compilations.all { compilation ->
            // Setup correct compiler options
            // FIXME AUTO-SETUP Are these to dangerous to apply under the hood?
            when (val options = compilation.kotlinOptions) {
                is KotlinJvmOptions -> {
                    options.jvmTarget = "1.8"
                }
            }
        }
    }
```

**In this plugin:**

`id("io.realm.kotlin") version "1.9.0" apply false`

### Stacktrace & log output

```shell
FT ~ Opusrornnetarsshop tied A: 2705 202800 730% Execution failed for task ' :app:kaptGenerateStubsDebugKotLin’ .

> Inconsistent JVM-target compatibility detected for tasks ‘compileDebugJavaWithJavac' (17) and ‘kaptGenerateStubsDebugkotLin' (1.8).

* Try:
> Run with --info or =-debug option to get more log output.
> Run with --scan to get full insights.

> Get more help at https://nelp.aradle.org.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. use `id("io.realm.kotlin") version "1.9.0" apply false`
2. try to change jvmTarget to 17

### Version

14

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android

### Build environment

Android Studio version: Koala | 2024.1.1
Android Build Tools version: 8.4.1
Gradle version: 3.2-8.5

**Comment by rorbech** [comment]
This was removed in https://github.com/realm/realm-kotlin/pull/1514 and hasn't been part of our releases since 1.12.0. Please try to use a more recent version.

**Comment by Efimj** [comment]
Thanks 💜
