### ISSUE TITLE
Auto migration is not working when adding a new property

### ISSUE THREAD

**Issue by sembozdemir** [realm/realm-kotlin#1771]
### How frequently does the bug occur?

Always

### Description

I am expecting that auto migration should work according to the documentation [here](https://www.mongodb.com/docs/atlas/device-sdks/sdk/kotlin/realm-database/schemas/change-an-object-model/#add-a-property) when I add a new property. However, it is failing for some reason. I guess there is a bug or am I missing something? Could you please help with it?

```
const val realmSchemaVersion = 3L // it was 2L

private val config = RealmConfiguration
  .Builder(setOf(MessageRealmObject::class, PendingMessageRealmObject::class))
  .schemaVersion(realmSchemaVersion)
  .build()

@Keep
private class MessageRealmObject : RealmObject {
    @PrimaryKey
    var _id: String? = null
    var chatId: String? = null
    var role: String? = null
    var text: String? = null
    var createdAt: Long? = null
    var photoId: String? = null // new property
    var photoImageUrl: String? = null // new property
}

@Keep
private class PendingMessageRealmObject : RealmObject {
    @PrimaryKey
    var _id: RealmUUID = RealmUUID.random()
    var chatId: String? = null
    var text: String? = null
    var createdAt: Long? = null
}

private fun <T> withRealm(func: (realm: Realm) -> T): T {
    val realm: Realm = Realm.open(config)
    val returnValue = func(realm)
    realm.close()
    return returnValue
}

fun example() {
   // it crashes when withRealm is called.
   withRealm {}
}
```

**Expected behavior**
Auto migration should work

**Actual behavior**
App crashes with the following exception.

### Stacktrace & log output

```shell
java.lang.IllegalStateException: [RLM_ERR_SCHEMA_MISMATCH]: Migration is required due to the following errors:
  - Property 'MessageRealmObject.photoId' has been added.
  - Property 'MessageRealmObject.photoImageUrl' has been added.
```

### Can you reproduce the bug?

Always

### Version

1.16.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 34

### Build environment

Android Studio version: Android Studio Hedgehog | 2023.1.1 Patch 
Gradle version: 8.2

**Comment by rorbech** [comment]
Hi @sembozdemir. I have no issues updating and migrating from version 2->3 while adding the new properties. Are you sure that you updated the `realmSchemaVersion` and added `photoId` and `photoImageUrl` in the same go? 

If you bump the version number and reboot the app without adding the properties, the schema will already have version 3. You will have to increment it again when adding the properties.

Otherwise please provide more details on how should be able to reproduce it in our end.
