### ISSUE TITLE
Ability to switch user

### ISSUE THREAD

**Issue by tomcully** [realm/realm-kotlin#1813]
### Problem

There looks like there isn't any way to Change the Active User on the Kotlin SDK at the moment. It looks like it's on all the other (or at least most other) language sdks

### Solution

adding `app.switch(to: secondUser)` to the sdk

### Alternatives

I've considered logging in every time. However, calling "app.login" doesn't work whilst offline

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Atlas App Services: Auth or Functions etc

**Comment by nirinchev** [comment]
This looks like an oversight. We should be able to add that fairly quickly though.
