### ISSUE TITLE
Evaluate if `RealmObject.version` is the best way to expose it

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#219]
Right now `RealmObject.version` is an extension method, but the plan was to move it to an interface method. This has a number of complications though:

- `version` is a very generic name and there is a high chance it conflict with user code
- If we change it to e.g. `realmVersion`, should we also change `Realm.version`, `RealmResults.version` and `RealmList.version` ?
- Exposing it as `RealmObject.realm.version` also seems problematic as we don't have multiple Realm instances.

This PR is about evaluating what the best way of doing it is? variable or function? And what the final name should be.

**Comment by cmelchior** [comment]
Also consider if all `version` parameters should be behind a `Versioned` interface or similar

**Comment by rorbech** [comment]
> variable or function? 

Remember to have the [Kotlin guidelines](https://kotlinlang.org/docs/coding-conventions.html#functions-vs-properties) in mind. At least our initial implementation can throw and change over time.
