### ISSUE TITLE
dlopen failed: library "librealmc.so" not found

### ISSUE THREAD

**Issue by beselam** [realm/realm-kotlin#221]
I was trying to run the calculator kmm example and when i call the calculator class from the android module am getting this error

androidRuntime: FATAL EXCEPTION: main
    Process: com.example.kmmapp.android, PID: 12978
    java.lang.UnsatisfiedLinkError: dlopen failed: library "librealmc.so" not found

**Comment by rorbech** [comment]
We currently only support 64-bit architectures (rest is tracked by #72, #109)

@beselam What architecture are you running it on?

**Comment by beselam** [comment]
macbook Intel Core i7 64bit

**Comment by rorbech** [comment]
@beselam What is the architecture of the Android device that you are trying to execute it on?

**Comment by beselam** [comment]
am  using  pixel 3a XL API 30 from the android studio emulator

**Comment by rorbech** [comment]
Please ensure that you are running it on an 64-bit emulator/device. 
```
adb shell getprop ro.product.cpu.abi
``` 
should yield something indicating that is an 64-bit architecture, i.e. `x86_64`.

**Comment by beselam** [comment]
thanks a lot the problem from from my emulator it is x86
it should run on an actual device right?

**Comment by beselam** [comment]
thanks for the help , i have also installed a x86_64 image for the emulator and it is working on both my phone and emulator . you can close this issue

**Comment by tquean15012003** [comment]
@rorbech Hi, when I tried to run the application on arm64-v8a, the emulator is shut down immediately after I clicked run. Do you know how to fix it?
<img width="644" alt="Screenshot 2024-01-24 at 1 44 31 PM" src="https://github.com/realm/realm-kotlin/assets/96300746/04c76118-c5f6-44e4-8c4f-3bc7ea525ecf">

**Comment by cmelchior** [comment]
Hi @tquean15012003 Please create a new issue, but this commonly happens if you have set the `Build Variants` do a different architecture than what the emulator is running
