### ISSUE TITLE
unable to connect with realm database on an actual device

### ISSUE THREAD

**Issue by beselam** [realm/realm-kotlin#224]
I was managed to access the realm database file on an emulator  and open it with realm studio for both ios and android .  i did not find anyway to connect with the real device realm database. can you please tell if there is a way to connect with real device.

**Comment by rorbech** [comment]
It is not possible to connect Realm Studio with the database on a real device.

**Comment by beselam** [comment]
ok. is there anyway to have a realtime access of the database  for debugging
