### ISSUE TITLE
Why i am not able to import below runtimeapi

### ISSUE THREAD

**Issue by naparam** [realm/realm-kotlin#257]
import io.realm.runtimeapi.RealmModel
import io.realm.runtimeapi.RealmModule
import io.realm.runtimeapi.RealmObject

**Comment by cmelchior** [comment]
Hi @narpatdesai 

We need more information in order to help you. Can you either provide your full project gradle setup or a sample project reproducing the issue?

**Comment by rorbech** [comment]
You are most likely using an outdated version. The `runtimeapi` packages was removed prior to 0.2.0. Please update to the latest version and provide additional details if the issue persists.
