### ISSUE TITLE
How do I sync data to MongoDB Atlas?

### ISSUE THREAD

**Issue by tiagonuneslx** [realm/realm-kotlin#287]
Are the sync capabilities available in this new SDK?

Also, do you have a Slack channel or some way to communicate directly with the community?

Thanks for your attention and for focusing on KMP!

**Comment by cmelchior** [comment]
Hi @tiagonuneslx 

We currently don't have a public Slack channel, but maybe something we should consider. Right now Github is the primary way to get in touch.

We are currently focusing on getting the local database API's in beta-state, after which we will implement the Sync functionality required to Sync with MongoDB. So right now, that isn't possible.

**Comment by cmelchior** [comment]
Folding this issue into https://github.com/realm/realm-kotlin/issues/197
