### ISSUE TITLE
Readme Setup red marker missing in buildscript repositories

### ISSUE THREAD

**Issue by tiagonuneslx** [realm/realm-kotlin#288]
The red marker is missing in this line, in the readme.md:

```kotlin
buildscript {
   repositories {
        // ...
        maven(url = "https://oss.jfrog.org/artifactory/oss-snapshot-local") <--
   }
}
```

![image](https://user-images.githubusercontent.com/49025614/121670336-373b9b80-caa5-11eb-8aae-49339fddfa95.png)

**Comment by rorbech** [comment]
Thanks for the report, but closing as it is outdated. We removed the images for maintenance reasons.
