### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by softartdev** [realm/realm-kotlin#295]
I have not found a way to encrypt in the Kotlin Multiplatform library like in the [Android](https://docs.mongodb.com/realm/sdk/android/advanced-guides/encryption/) / [iOS](https://docs.mongodb.com/realm/sdk/ios/advanced-guides/encrypt-a-realm/) platform libraries.
Obviously this has not been implemented yet and we request to support this feature.

**Comment by rorbech** [comment]
Thanks for the input. We already have an issue to track this #227. I have updated the description of that to actually indicate what is was about and will close this as a duplicate.
