### ISSUE TITLE
Multiplatform gradle implementatin issue

### ISSUE THREAD

**Issue by easedroid** [realm/realm-kotlin#321]
I am very new to multiplatform, since I have worked on Android I tried accordingly.

This is what I got:

`Could not find io.realm.kotlin:cinterop-jvm:0.3.0.
Required by:
    project :desktop > io.realm.kotlin:library-jvm:0.3.0 > io.realm.kotlin:cinterop:0.3.0`

Please help me out.

**Comment by cmelchior** [comment]
It sounds like you are trying to build for JVM, which we don't support fully yet. You can follow #62 for that.

**Comment by easedroid** [comment]
Yes, I am working on Desktop version also. Hopefully it will be solved by the community soon.
