### ISSUE TITLE
[Frozen Architecture] Merge Realm Core branch with freeze/thaw methods

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#328]
The Frozen Architecture currently depends on features not merged to Core/master. We should get the PR merged to avoid having to deal with keeping the branch up to date.

The C-API is currently throwing an error when thawing a deleted object. Current implementation catches this and returns null, but should instead be fixed in the Core PR: https://github.com/realm/realm-core/pull/4658

**Comment by rorbech** [comment]
https://github.com/realm/realm-core/pull/4658 is now merged in core, so we can now update our freeze/thaw implementation to used the updated C-API. Our API is already partially update to this in #440, so should just be a matter of renaming according to the latest changes.
