### ISSUE TITLE
Cannot resolve dependency

### ISSUE THREAD

**Issue by TonnyL** [realm/realm-kotlin#361]
Error message:

```
Could not find io.realm.kotlin:cinterop-jvm:0.5.0-SNAPSHOT.
Required by:
    project :desktop > project :common > io.realm.kotlin:library:0.5.0-SNAPSHOT:20210715.121820-5 > io.realm.kotlin:library-jvm:0.5.0-SNAPSHOT:20210715.121820-5 > io.realm.kotlin:cinterop:0.5.0-SNAPSHOT:20210715.121820-5

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

I'm using realm-kotlin 0.5.0-SNAPSHOT. And here is my project structure:

<img width="282" alt="Screen Shot 2021-07-27 at 4 08 28 PM" src="https://user-images.githubusercontent.com/13329148/127120008-4bd36e58-b498-4145-a72d-7fc8f7a7c279.png">

**Comment by rorbech** [comment]
We currently don't support pure JVM targets. It is on our roadmap, but we don't have an ETA yet. Closing this issue as it is already tracked through #62.
