### ISSUE TITLE
Crash in toString method on field of type Int? with default null 

### ISSUE THREAD

**Issue by promanowicz** [realm/realm-kotlin#374]
toString called on field of type Int? with default value 'null' will throw exception when object is queried from realm 
eg:
```
class SomeObj : RealmObject(){
   ...
   var faultyInt : Int?=null 
}

realm.objects(SomeObj::class).findFirst().faultyInt?.toString()
```

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Number.longValue()' on a null object reference`

build android
realm version "0.4.1"
kotlin + plugin "1.5.21"
java version "11.0.12"

**Comment by rorbech** [comment]
Thanks for the report. Seems like our internal unboxing doesn't check for null.
