### ISSUE TITLE
Custom methods in model classes use initializer values

### ISSUE THREAD

**Issue by promanowicz** [realm/realm-kotlin#375]
```
class SomeObj : RealmObject(){
   ...
   var someVar : Int=100
   
   fun customPrinter():String{
      return "myInt: " + someVar
   }
}

```
use of customPrinter() will print 100 altough some different value has been set to the field
eg:
realm.objects(SomeObj::class).findFirst()?.apply{
   customPrinter() + " " + someVar 
}
will print "myInt: 100 9" if actual value of someVar is 9

build android
realm version "0.4.1"
kotlin + plugin "1.5.21"
java version "11.0.12"

**Comment by rorbech** [comment]
Interesting 🤔. I will have to inspect the IR to understand what is going on here. Maybe there is some optimization in effect or some other reason why our getter is not taken into account.

**Comment by rorbech** [comment]
It was in fact a missing property on the accessors that triggered optimization on the JVM IR backend.
