### ISSUE TITLE
Unable to open a realm at path 'testing.lock'. Please use a path where your app has read-write permissions.

### ISSUE THREAD

**Issue by shalva97** [realm/realm-kotlin#380]
okay so im suffering with testing. I want to specify custom path for the database file like this
```
private val config = RealmConfiguration(schema = setOf(TaskEntity::class, TabEntity::class), path = "testing")
```
but then it complains, it only works if I do not pass anything to `path` parameter.
![image](https://user-images.githubusercontent.com/22417494/129790474-2b078309-07df-4ffd-ad6f-dffb1cfac344.png)

**Comment by rorbech** [comment]
The path should be an absolute path. The API for just setting the name of the realm file is `RealmConfiguration.Builder().name(...)` but unfortunately this is currently broken (#346).

**Comment by mehmetakify** [comment]
Setting name function fixed but I couldnt realize what should be the absolute path to work all mac desktops. I try somethings but the same error continues. Could you give an example for the absolute path?
