### ISSUE TITLE
Add support for RealmAny

### ISSUE THREAD

**Issue by edualonso** [realm/realm-kotlin#536]
The API should look something like this:
```
public interface RealmAny {

    public enum class Type {
        INT, BOOLEAN, STRING, BYTE_ARRAY, REALM_INSTANT, FLOAT, DOUBLE, OBJECT_ID, REALM_UUID, REALM_OBJECT
    }

    public val type: Type

    public fun asShort(): Short
    public fun asInt(): Int
    public fun asByte(): Byte
    public fun asChar(): Char
    public fun asLong(): Long
    public fun asBoolean(): Boolean
    public fun asString(): String
    public fun asFloat(): Float
    public fun asDouble(): Double
    public fun asRealmObjectId(): ObjectId // support for legacy 
    public fun asObjectId(): BsonObjectId
    public fun asByteArray(): ByteArray
    public fun asRealmInstant(): RealmInstant
    public fun asRealmUUID(): RealmUUID
    public fun <T : BaseRealmObject> asRealmObject(clazz: KClass<T>): T

    companion object {
        // TODO constructors from interface or factory methods...?
        public operator fun invoke(value: Short): RealmAny = TODO()
        public operator fun invoke(value: Int): RealmAny = TODO()
        public operator fun invoke(value: Byte): RealmAny = TODO()
        public operator fun invoke(value: Char): RealmAny = TODO()
        public operator fun invoke(value: Long): RealmAny = TODO()
        public operator fun invoke(value: Boolean): RealmAny = TODO()
        public operator fun invoke(value: String): RealmAny = TODO()
        public operator fun invoke(value: Float): RealmAny = TODO()
        public operator fun invoke(value: Double): RealmAny = TODO()
        public operator fun invoke(value: ObjectId): RealmAny = TODO()
        public operator fun invoke(value: BsonObjectId): RealmAny = TODO()
        public operator fun invoke(value: ByteArray): RealmAny = TODO()
        public operator fun invoke(value: RealmInstant): RealmAny = TODO()
        public operator fun invoke(value: RealmUUID): RealmAny = TODO()
        public operator fun <T : BaseRealmObject> invoke(value: T): RealmAny = TODO()
    }
}
```
**Nullability**:
There are two options here: either we allow `RealmAny` instances to hold null values similarly to what we do in Java (https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmAny.java#L170) or we bake it inside Kotlin's type system similarly to what we do in `MutableRealmInt` (https://github.com/realm/realm-kotlin/blob/master/packages/library-base/src/commonMain/kotlin/io/realm/kotlin/types/MutableRealmInt.kt#L49). Finally, `RealmAny` properties must be declared nullable in the schema as per Core constraints to the `Mixed` type:
```
class RealmAnyContainer : RealmObject {
    var realmAnyField: RealmAny? = RealmAny(42)
    var anotherRealmAnyField: RealmAny? = null
    var nonNullableRealmAnyField: RealmAny = RealmAny(42) // This is not allowed by Core
}

// unmanaged case
val unmanagedContainer = RealmAnyContainer()
unmanagedContainer.anyField = null
unmanagedContainer.anyField = RealmAny("something")

// managed case
realm.writeBlocking {
    val managedContainer = copyToRealm(container)
    managedContainer.anyField = null
    managedContainer.anyField = RealmAny("something else")
}
```
**Wrapping `RealmObject`s**:
Embedded objects are not allowed, only ordinary `RealmObject`s are allowed inside `RealmAny`.

**Objects not declared in the schema**:
It is impossible to validate whether a particular class has been declared in the database schema for unmanaged `RealmAny` instances. However, managed instances should throw when doing something like this:
```
        val notInSchema = NotInSchema()
        realm.writeBlocking {
            val managedContainer = copyToRealm(RealmAnyContainer())
            val realmAnyWithClassNotInSchema = RealmAny(notInSchema)
            assertFailsWithMessage<IllegalArgumentException>("Schema does not contain a class named 'NotInSchema'") {
                managedContainer.anyField = realmAnyWithClassNotInSchema
            }
        }
```

**Support in collections**:
Lists and sets should be able to store `RealmAny` instances. The constraints regarding wrapping objects mentioned above apply here as well.

**Open questions**:
- Should we use factory methods, e.g.
```
    public companion object {
        public fun create(value: String): RealmAny = TODO()
    }

    // ...
    val realmAny = RealmAny.create("hello")
```
~~or the new `invoke` operator for interfaces~~
```
    public companion object {
        public operator fun invoke(value: String): RealmAny = TODO()
    }

    // ...
    val realmAny = RealmAny("hello")
```
~~to instantiate `RealmAny` objects? We use factories everywhere else in the SDK. Although using invoke seems neater in the sense that constructs the instance from the interface and has good visibility from the IDE.~~ We will use factories as that's the pattern we use everywhere else.

**Comment by ammerzon** [comment]
Any updates on this?

**Comment by edualonso** [comment]
We have just started working on it this feature this week. The initial approach we have chosen might entail somewhat big internal changes as the feature foundations could very well help us abstract the conversion between C-API and the SDK-exposed data types better. But to reassure you, we are on it 😉

**Comment by ammerzon** [comment]
That's awesome to here. Thank you for your fast reply 😁
