### ISSUE TITLE
Multiplatform build fails when not using Realm in all source sets

### ISSUE THREAD

**Issue by FERNman** [realm/realm-kotlin#544]
When using the Realm Gradle plugin (0.7.0) in a multiplatform project, the build fails for source sets not using the Realm library (in our case, the JVM) with the following error message:

```
java.lang.IllegalStateException: Cannot find io.realm.RealmConfiguration.Builder on platform JVM (JVM_1_8).
```

This was not the case with older versions of the plugin (we upgraded from 0.4.1). As far as I can tell, it was introduced by #395.
The issue comes from the schema lowering extension that tries to find [the realm configuration builder](https://github.com/realm/realm-kotlin/blob/2b07af06553b49509c1d26c620f3fd0c009b6547/packages/plugin-compiler/src/main/kotlin/io/realm/compiler/RealmSchemaLoweringExtension.kt#L74) (and throws if it doesn't exist) before the builder was actually used for the first time.

**Comment by rorbech** [comment]
Thanks for the report. We tried to cache class lookups early to avoid duplicate look ups, but didn't think of the use case that the plugin is running on source sets that doesn't depend on our library.

**Comment by nhachicha** [comment]
@FERNman This has been fixed, you can try the SNAPSHOT [release](https://github.com/realm/realm-kotlin#using-snapshots), or wait for the upcoming `0.8.0` release.

**Comment by FERNman** [comment]
@nhachicha Thanks for the quick fix! 🙂
