### ISSUE TITLE
Add support for copyFromRealm

### ISSUE THREAD

**Issue by ptsiogas** [realm/realm-kotlin#549]
It would be convenient to add a method like copyFromRealm in order to be able to get unmanaged objects from the DB.

**Comment by ptsiogas** [comment]
I have done a little more research and I realised that in order to work with realm-kotlin in KMM you need to have 2 classes per object (e.g Person and PersonDB: RealmObject). I have seen that it's not possible to work with a realm object in the native Android or iOS code. 
This is a little frustrating and time consuming, especially when working with complex models.

So given the above, I do not think there is a case where copyFromRealm is really useful. Instead I would love to have an automated/simple way to create/transform a realm object into its display/UI model in order to work with it in the Native code.

**Comment by cmelchior** [comment]
>  have seen that it's not possible to work with a realm object in the native Android or iOS code.

What do you mean exactly by this? You should be able to reference RealmObjects in iOS and Android code even if they are defined in the shared module?

That said, we have been thinking about a projection feature that will make it possible to automatically convert from database objects to viewmodel-objects.

**Comment by ptsiogas** [comment]
Hmm interesting. I am getting a compile error when trying to use a RealmObject, defined in the shared module, in the Android native code. I will try to post some logs today.

**Comment by cmelchior** [comment]
You will need to add the library to the dependencies for each specific platform to use the Realm types there. You can see an example for Android here: https://github.com/realm/realm-kotlin#setup
