### ISSUE TITLE
Support embedded objects

### ISSUE THREAD

**Issue by rorbech** [realm/realm-kotlin#551]
We should support defining realm objects as _embedded_ to indicate that object life cycle should follow its parent.

**Comment by rorbech** [comment]
Requires C-API support: https://github.com/realm/realm-core/issues/5408

**Comment by thipokch** [comment]
@rorbech I believe release 11.15.0 already included the C-API for embedded object: https://github.com/realm/realm-core/blob/master/CHANGELOG.md#11150-release-notes

**Comment by rorbech** [comment]
> @rorbech I believe release 11.15.0 already included the C-API for embedded object: https://github.com/realm/realm-core/blob/master/CHANGELOG.md#11150-release-notes

Yep. The core part is already in place, but still requires some work in the actual SDK - #797.

**Comment by thipokch** [comment]
@rorbech Congrats on the GA release! 🎉  I'm so looking forward to trying embedded objects out.

**Comment by rorbech** [comment]
> Quick question: Does the embedded object support a sealed interface polymorphism as RealmObject does?

We don't support polymorphic inheritance on neither `RealmObject` nor `EmbeddedObject`. You can track support for that through #801.
