### ISSUE TITLE
RealmConfiguration.path should report the full Realm

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#605]
When debugging, seeing errors like this:

```
Migration is required due to the following errors:
- Property 'WorkType._id' has been changed from 'int' to 'string'. Could not open Realm with the given configuration: path=./default.realm
```

Make it hard to find the Realm that is being opened. We should convert all user input paths to an absolute path.

**Comment by Reedyuk** [comment]
If you set the log level to all in the config.

```
val realmConfig = RealmConfiguration.Builder()
        .path(databaseFile)
        .log(LogLevel.ALL)
        .build()
    val realm = Realm.open(realmConfig)
```

You will see in the logs Realm opened: /data/user/0/android.searchFlowPrototype/cache/default.realm
