### ISSUE TITLE
Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)

### ISSUE THREAD

**Issue by TomWayne98** [realm/realm-kotlin#616]
I am using Realm Kotlin Multiplatform SDK in version 0.7. 

So far it worked fine but I am getting this error: 

 ```
Caused by: io.realm.internal.interop.RealmCoreNotInATransactionException: [5]: Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)
    Exception backtrace:
    <backtrace not supported on this platform>
        at io.realm.internal.interop.CoreErrorUtils.coreErrorAsThrowable(CoreErrorUtils.kt:29)
        at io.realm.internal.interop.realmcJNI.realm_object_delete(Native Method)
        at io.realm.internal.interop.realmc.realm_object_delete(realmc.java:455)
        at io.realm.internal.interop.RealmInterop.realm_object_delete(RealmInterop.kt:626)
        at io.realm.internal.MutableRealmImpl.delete(MutableRealmImpl.kt:114)
```

whenever I run this block of code: 

```
response.value.orEmpty().map {
                                val ticket = it.toRealmTicket()
                                val alreadyExistingTicket = db.objects<RealmTicket>().query("number == $0", ticket.number.toString()).firstOrNull()
                                if (alreadyExistingTicket?.isValid() == true) {
                                    db.writeBlocking {
                                        this.delete(alreadyExistingTicket)
                                    }
                                }
                                db.writeBlocking {
                                    this.copyToRealm(ticket)
                                }
                            }
```

Am I doing something wrong?

**Comment by rorbech** [comment]
Hi @TomWayne98 Seems like you are just trying to delete a _frozen_ reference which is practically a snapshot of the data from the point in time where you obtained the reference. Since this could be outdated you have to obtain a reference to the object _inside_ the write transaction with `findLatest`. You can see an example of this at https://github.com/realm/realm-kotlin#update.

**Comment by nirinchev** [comment]
This looks like a very common pitfall, so we should probably explicitly detect it and throw a more meaningful exception or - maybe better - do a `findLatest` internally and delete the live reference if found.

**Comment by cmelchior** [comment]
Yes, I thought we already tracked it here: https://github.com/realm/realm-kotlin/issues/297, but that was just for updates. Apparently, this was forgotten. But I agree that the behavior around this needs to be improved. As a minimum with a better error message.
