### ISSUE TITLE
Feature: Android Support passing in bundle asset

### ISSUE THREAD

**Issue by Reedyuk** [realm/realm-kotlin#625]
I have a use case where i am bundling my realm in the application.
When using ios i can give the file path directly and reliably know that the path is correct.
In Android, i cannot guarantee as this can differ per manufacturer, instead the recommended approach is to pass an asset file

https://docs.mongodb.com/realm/sdk/android/examples/bundle-a-realm/

```
val config = SyncConfiguration.Builder(
app.currentUser(),
"PARTITION_YOU_WANT_TO_BUNDLE")
.assetFile("example_bundled.realm")
.build()
```

The current api for this project doesnt expose such a thing.

**Comment by cmelchior** [comment]
Agree, this is something we want to add. We already have an issue tracking it here: https://github.com/realm/realm-kotlin/issues/577, so closing this as a duplicate.
