### ISSUE TITLE
Support MongoDB ObjectId field type

### ISSUE THREAD

**Issue by rorbech** [realm/realm-kotlin#652]
We should support the MongoDB ObjectId field type: https://docs.mongodb.com/manual/reference/method/ObjectId/

**Comment by sdeff** [comment]
Any updates about when we can expect support for `ObjectId`?

Or is there a workaround which allows using a RealmObject with `ObjectId` as primary key within a Kotlin Multiplatform app?

**Comment by tylergannon** [comment]
@sdeff what about defining your own `value class ObjectId(val id: ByteArray)`, then the database column will contain compatible data for when the feature is released?  It's hacky but might get you going?


you can `expect` the constructors and implement them by delegating to the `org.bson.types.ObjectId` implementation.

```
expect fun ObjectId(): ObjectId
expect fun ObjectId(hexValue: String): ObjectId
```

Untested so ymmv.  I'd be curious if someone more knowledgable than this relative noob could say _a priori_ that it won't work.
