### ISSUE TITLE
Support for Decimal128 field types

### ISSUE THREAD

**Issue by rorbech** [realm/realm-kotlin#653]
We should add support for Decimal128 field types similar to realm-java: https://github.com/realm/realm-java/issues/6712

**Comment by cmelchior** [comment]
KBSON currently doesn't high/low in the public API. We need to expose that to be able to send Decimal128's into Core

**Comment by cmelchior** [comment]
The needed properties have been merged and should be available in a 0.2.0-SNAPSHOT soon
