### ISSUE TITLE
Cannot find io.realm.internal.interop.ClassInfo on platform JVM (JVM_1_8)

### ISSUE THREAD

**Issue by astatio** [realm/realm-kotlin#662]
Similar to issue #544 

> java.lang.IllegalStateException: Cannot find io.realm.internal.interop.ClassInfo on platform JVM (JVM_1_8)

It is suggested in the said issue to use 0.8.0 (presumably, at the time it was not yet available) which would fix the problem.
I'm currently using 0.9.0 
Rolling back to 0.8.0 did fix the issue, but can this be fixed so it does not happen with newer versions?

I would like to add that I am only compiling to JVM.

Thanks

**Comment by cmelchior** [comment]
Hi @astatio Can you try to post your build.gradle files?

**Comment by astatio** [comment]
https://pastebin.com/6zYS1Djk

**Comment by rorbech** [comment]
I don't think this is the same root cause as #544 as we should now have tests compiling a source set without our dependency. Do you mind sharing a bit more details, i.e. the whole stack trace, gradle task that fails, etc.? ... And have you tried doing a clean build?

**Comment by nhachicha** [comment]
@astatio I tried using your Gradle configuration on the [JVMConsole](https://github.com/realm/realm-kotlin-samples/tree/main/JVMConsole) project but couldn't reproduce the issue.
here is the link to the updated [sample](https://drive.google.com/file/d/1DRzvnx7zUsC3voqd_peZ3PkEisOumUAe/view?usp=sharing) 
I'm able to compile and build a jar using `./gradlew clean uberJar`

It will be helpful if you manage to update the sample I've shared with you, to somehow reproduce the issue, so we can investigate

**Comment by astatio** [comment]
> @astatio I tried using your Gradle configuration on the [JVMConsole](https://github.com/realm/realm-kotlin-samples/tree/main/JVMConsole) project but couldn't reproduce the issue. here is the link to the updated [sample](https://drive.google.com/file/d/1DRzvnx7zUsC3voqd_peZ3PkEisOumUAe/view?usp=sharing) I'm able to compile and build a jar using `./gradlew clean uberJar`
> 
> It will be helpful if you manage to update the sample I've shared with you, to somehow reproduce the issue, so we can investigate

That surprisingly solved the issue. Thank you.
