### ISSUE TITLE
Currently no way to handle migrations?

### ISSUE THREAD

**Issue by CarsonRedeye** [realm/realm-kotlin#685]
I'm seeing migration errors when opening a realm with some properties changed i.e.
Caused by: io.realm.internal.interop.RealmCoreLogicException: [18]: Migration is required due to the following errors:

However, I don't see that there is any API available to handle migrations? Is this correct? I see that there is a draft PR here
https://github.com/realm/realm-kotlin/pull/674
but is there any way at all to perform migrations currently, no matter how manual?

**Comment by rorbech** [comment]
No, there is no way to migrate your realm before #674 is merged. Only option before that is to trigger deletion of the old realm with [`deleteRealmIfMigrationNeeded`](https://github.com/realm/realm-kotlin/blob/master/packages/library-base/src/commonMain/kotlin/io/realm/RealmConfiguration.kt#L56). As you already noted it is work in progress, so hopefully it will be available in a snapshot soon.

**Comment by CarsonRedeye** [comment]
@rorbech Could you give a timeline of when the first migration API will hit snapshot? 1 month, 6 months, or 1 year?

**Comment by rorbech** [comment]
@CarsonRedeye Either late this week or sometime next week.
