### ISSUE TITLE
Evaluate use of C++ runtime

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#710]
Right now it looks like we are bundling `libc++_shared.so` in our cinterop package. This is causing problems with other libraries if they do not agree on the NDK version. Surfacing as errors such as these: https://github.com/realm/realm-kotlin/issues/694.

Looking at Realm Java, it doesn't look like we are bundling `libc++_shared` which probably means we are using `libc++_static` instead. At least according to the documentation: https://developer.android.com/ndk/guides/cpp-support#selecting_a_c_runtime

We should investigate why there is such a difference between Realm Java and Realm Kotlin and what would be the most appropriate choice for Realm Kotlin.

**Comment by cmelchior** [comment]
Probably also relevant to #216

**Comment by rorbech** [comment]
I revived an old PR to use the static runtime in #620
