### ISSUE TITLE
the same architectures (arm64) and can't be in the same fat output file

### ISSUE THREAD

**Issue by Charon1997** [realm/realm-kotlin#721]
I encountered this problem when I compiled it , This is the error details.

` Task :linkDebugFrameworkIosFat FAILED
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /../build/bin/iosX64/DebugFramework/xx.framework/xx and /../build/bin/iosArm64/DebugFramework/xx.framework/xx have the same architectures (arm64) and can't be in the same fat output file`

**Comment by cmelchior** [comment]
Hi @Charon1997 Are you trying to create a static library, similar to https://github.com/realm/realm-kotlin/issues/722?

**Comment by Charon1997** [comment]
hi，我已经收到你的邮件了，我会尽快查看的~

**Comment by Charon1997** [comment]
> Hi @Charon1997 Are you trying to create a static library, similar to #722?

Yes, encountered the same problem as #722.

**Comment by cmelchior** [comment]
Okay, closing this as an duplicate then. Please follow #722 for updates.

**Comment by Charon1997** [comment]
> Okay, closing this as an duplicate then. Please follow #722 for updates.

Okay, hopefully this will be resolved soon.
