### ISSUE TITLE
Internal refactor: Split RealmInterop and Typesafe NativePointers

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-kotlin#725]
From #713 

(Claus -2) Type safety of NativePointer. Maybe by generic marker type (NativePointer<Realm>, NativePointer<RealmObject>, etc.). Maybe it's better to do actual specific typed instance like the realm-java OSs, so requires some thought/experiments. 

Closed by #760

**Comment by rorbech** [comment]
Moved spill over sub tasks to #792
