### ISSUE TITLE
Opening a realm keeps the thread alive forever

### ISSUE THREAD

**Issue by jakobkmar** [realm/realm-kotlin#769]
Opening a realm keeps the thread alive forever, even if `Realm::close` is called.
This makes it impossible to exit the application correctly.

Tested on:
Realm version: 0.10.1
Platform: JVM Java 17 on Windows x86_64

Possibly related to #733

**Comment by cmelchior** [comment]
Hi @jakobkmar Thank you for the report. I strongly suspect the root cause of this is the same as #733, so I'll be closing this as a duplicate. You can follow #733 for updates.
