### ISSUE TITLE
Provide suspending query functions which do not observe future changes

### ISSUE THREAD

**Issue by jakobkmar** [realm/realm-kotlin#786]
Currently it is already possible to query the database in a suspending way, but only by using the API which then also observes changes, meaning we have to filter for `InitialResults<T>` only and then ignore future changes published to the flow.
The workaround in the docs: https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/read/find-objects-of-a-type/

Another possibility I have thought of might be to only collect the first element of the changes flow, but I am not sure whether that is safe and closes all resources correctly? Also this solution might not be as performant as a suspending query function could be.

**Comment by cmelchior** [comment]
If you want a query that runs in the background and only returns the first result you can use the `first()` extension method on Flows which will turn it into a suspending call: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/first.html.

Like this:
```
suspend fun firstResult(searchName: String): RealmResults<Person> {
  realm.query<Person>("name = $0", searchName)
    .asFlow()
    .first() // Terminate flow when first result is received, this turns the Flow into a normal suspending call
}
```

I don't know if that answers your question?

**Comment by jakobkmar** [comment]
This approach is what I meant in the second half of my question, but I am still wondering if this closes all resources correctly?

In `SingleQuery::asFlow` the following is called: `realmReference.owner.registerObserver(this)`, and I am not sure if it will ever get "unregistered" if I do `asFlow().first()`.

**Comment by cmelchior** [comment]
It will. The relevant code is here: https://github.com/realm/realm-kotlin/blob/master/packages/library-base/src/commonMain/kotlin/io/realm/internal/SuspendableNotifier.kt#L119 ... as long as the Flow is closed (which calling `first()` will do), then we should clean things up correctly.

**Comment by jakobkmar** [comment]
Alright, thanks for the clarification, good to know that this is a safe way for suspending queries 👍 - and sry for the late reply.
