### ISSUE TITLE
IncorrectDereferenceException: Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread

### ISSUE THREAD

**Issue by XandrMaster** [realm/realm-kotlin#799]
Hello guys . I have an exception and crash only for iOs when I config my Real from non-main thread :( . Take a look pls to source code:
```
@ThreadLocal
object RealmManager {

    val realmDb by lazy { initRealmAsync() }

    private fun initRealmAsync(): Deferred<Realm> {
        return CoroutineScope(Dispatchers.Default).async {
            val config = RealmConfiguration.Builder(
                schema = setOf(
                    UserEntity::class,
                    EquipmentEntity::class,
                    UserActionEntity::class))
                .log(LogLevel.ALL)
                .schemaVersion(1)
                .build()
            Realm.open(config)
        }
    }

    fun forceInit() {
        CoroutineScope(Dispatchers.Default).launch {
            realmDb.await()
        }
    }
}
```

if I calling `forceInit()` from iOs it crashes . This code in common module . For Android works fine .
With `Dispatchers.Main` all good.
Thanks .

**Comment by cmelchior** [comment]
Hi @XandrMaster Can you provide a bit more information:

- What code do you run to see this error? 
- What version of the Realm Kotlin SDK?
- Version of coroutines?
- Version of Kotlin?

Also, any reason you are making the `RealmManager` ThreadLocal? The Kotlin SDK no longer requires the Realm instance to to locked to a specific thread, so you can just open a single global instance.

**Comment by rorbech** [comment]
@XandrMaster Could you also please supply the stack trace from the error to indicate which top level value that is causing the issue?
