### ISSUE TITLE
Support UpdatePolicy.ALL for RealmList.add

### ISSUE THREAD

**Issue by t7costa** [realm/realm-kotlin#849]
It is currently not possible with RealmList to add multiple items with the same primary key (or for different lists to add an item with the same primary key)
RealmListInternal uses UpdatePolicy.ERROR for its insert operators (https://github.com/realm/realm-kotlin/blob/master/packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmListInternal.kt#L197) which differs from the behaviour in realm-java (which  uses copyToRealmOrUpdate when adding unmanaged objects to a managed RealmList https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmList.java#L214)

```
class TestList: RealmObject {
    var items: RealmList<TestItem> = realmListOf()
}

class TestItem : RealmObject {
    @PrimaryKey var id: String = "1"
}
```

```
realm.write {
    val myList = copyToRealm(TestList())
    myList.items.add(TestItem())
    myList.items.add(TestItem())
}
```

```
realm.write {
    val testList1 = copyToRealm(TestList())
    val testList2 = copyToRealm(TestList())

    testList1.items.add(TestItem())
    testList2.items.add(TestItem())
}
```
java.lang.IllegalArgumentException: Failed to create object of type 'TestItem': RealmCoreException([33]: Object with this primary key already exists)

**Comment by cmelchior** [comment]
Hi @t7costa 
Thank you for this. You are correct, we should have the same semantics as Realm Java. We will fix this.
