### ISSUE TITLE
User exceptions are not signalled during DiscardLocalChangesStrategy callbacks on Kotlin native

### ISSUE THREAD

**Issue by clementetb** [realm/realm-kotlin#867]
We are not able to properly handle user exceptions during the `DiscardLocalChangesStrategy.onBeforeReset()` and `DiscardLocalChangesStrategy.onAfterReset()' on mac os. 

We need a way to properly signal core that an exception has ocurred.

The sync thread would crash in this situation. A work around would be to handle the exception manually on those callbacks.

**Comment by edualonso** [comment]
Will be fixed in #925
