### ISSUE TITLE
EmailPasswordAuth class Reset password function : wrong parameters order

### ISSUE THREAD

**Issue by eloigrndl** [realm/realm-kotlin#885]
Hello everybody!

I was using the resetPassword function from EmailPasswordAuth class and the documentation suggest the follwing function signature `resetPassword(token: String, tokenId: String, newPassword: String)`.

When using it that way I've always got the following response : `[Service][BadRequest(48)] invalid token data`

I tried changing the parameters order when calling the function (as this issue was already raised for other SDKs) like this : `app.emailPasswordAuth.resetPassword(newPassword, token, tokenId)` instead of `app.emailPasswordAuth.resetPassword(token, tokenId, newPassword) `and that time it worked.

Hence, there might be a problem in the function signature or elsewhere.

**Comment by rorbech** [comment]
@eloigrndl Thanks for the report
