### ISSUE TITLE
Crash: Failure when computing UTF-16 size

### ISSUE THREAD

**Issue by sheinin** [realm/realm-kotlin#895]
### How frequently does the bug occur?

Sometimes

### Description

Android App crashed intermittently after upgrade to 1.0.0

### Stacktrace & log output

```shell
1655256275.582 E/libc++abi: terminating with uncaught exception of type realm::util::ExceptionWithBacktrace<std::runtime_error>: Failure when computing UTF-16 size error_code = 1; retcode = 16; StringData.size = 57; StringData.data = 
    Exception backtrace:
    <backtrace not supported on this platform>
```

### Can you reproduce the bug?

Yes, sometimes

### Reproduction Steps

Crashes any time while the app is open

### Version

1.0.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 11

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by cmelchior** [comment]
Hi @sheinin 

This looks like a problem when reading out a String. It shouldn't just happen without you initiating some action. Do you have the full stack trace?

**Comment by cmelchior** [comment]
@sheinin If you are using Device Sync, do you mind sharing the app id. That way we can look up the logs and see if anything weird is showing up.

You can share it privately with christian.melchior@mongodb.com

**Comment by cmelchior** [comment]
Hi @sheinin Thank you, we got the App ID and is looking into it.

**Comment by cmelchior** [comment]
@sheinin If possible, could you also send any Atlas App Service errors you have? They should be here:

![image](https://user-images.githubusercontent.com/406066/174644675-937c1774-1119-4e17-af30-ae7272f6739d.png)

**Comment by edualonso** [comment]
Hi @sheinin. We have merged a pull request in connection with this bug and it will be available in the upcoming release. Please let us know if you still experience this issue after we release the fix.
