### ISSUE TITLE
CertificateException: Domain specific configurations require that hostname aware checkServerTrusted(X509Certificate[], String, String) is used

### ISSUE THREAD

**Issue by sdeff** [realm/realm-kotlin#900]
Hi,

I'm setting up a minimal Realm Kotlin (Android only) sample but as soon as I call:

`app.login(Credentials.anonymous())`

I get the following ConnectionException:
`[Custom][Unknown(1002)] java.security.cert.CertificateException: Domain specific configurations require that hostname aware checkServerTrusted(X509Certificate[], String, String) is used.`

As I just followed the official documentation: Do you have any ideas what's wrong?

**Comment by cmelchior** [comment]
We have seen that issue before. That was when running on an older Android emulator, and upgrading to the latest version fixed it.

What device/emulator are you seeing this on?

**Comment by sdeff** [comment]
Unfortunately I'm getting this exception with all my devices (latest emulator version 31.3.7 with Android API 32, Samsung Galaxy S10 with Android 12 and Google Pixel 6 Pro with Android 13)

**Comment by edualonso** [comment]
Hi @sdeff. We have tried different setups with different x86 emulators and two physical devices (Pixel 6 and 3) and couldn't reproduce the error you are seeing. Are you using any specific network settings we should be aware of?

**Comment by sdeff** [comment]
I'm currently using a custom network-security-config for the local build that looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">localhost</domain>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </domain-config>
</network-security-config>
```
When I remove this config, the `app.login()` call succeeds. Is there any need for a specific config for Realm Sync?

**Comment by edualonso** [comment]
> When I remove this config, the `app.login()` call succeeds. Is there any need for a specific config for Realm Sync?

No, you shouldn't need any specific network configuration to run Sync.

If you still need to have a domain-specific configuration please be aware of the existence of a bug in the Ktor library, which we use internally as our network transport for enabling Sync: https://youtrack.jetbrains.com/issue/KTOR-2243/Android-CIO-client-fail-with-javasecuritycertCertificateException#focus=Comments-27-5915979.0-0

**Comment by pvegh** [comment]
Thanks for that hint!
That bug bites us hard, we need this config for sad reasons like RN crap around the App.
Will look into a workaround...
Looks like the problem is not on realm's end, I think this can be closed.
