### ISSUE TITLE
Support for kotlinx-coroutines-core 1.6.3

### ISSUE THREAD

**Issue by GriffinJBC** [realm/realm-kotlin#921]
I have a project that has another dependency that depends on org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.3.
However if I include this in my gradle file I get met with a constraint error and am unable to build my project. 
Is it possible to run this repo with the updated coroutines core? (Or am I missing something else more obvious?)

**Comment by nhachicha** [comment]
Hi @GriffinJBC 
1- Is it a multiplatform or Android project?
2- What is the library using coroutine 1.3?
3- Have you tried using [strictly](https://kotlinlang.org/docs/multiplatform-mobile-concurrency-and-coroutines.html#multithreaded-coroutines) to force the usage of specific version 
```Kotlin
implementation ("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0-native-mt") {
    version {
        strictly("1.6.0-native-mt")
    }
}
```
