### ISSUE TITLE
Android build error when using data binding with realm object

### ISSUE THREAD

**Issue by robbieadi** [realm/realm-kotlin#923]
Hi, i have this problem.

If i have a class that inherits RealmObject
```
import io.realm.kotlin.types.RealmObject

class User: RealmObject {
    var name: String = ""
```

And i try to make it as live data
```
class LoginViewModel : ViewModel() {

    val user = MutableLiveData<User>()
```

And i use data binding to display its value somewhere in my layout
```
            <androidx.appcompat.widget.AppCompatTextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="@{viewModel.user.name}"
                tools:text="hi User"/>
```

I will get this error when i try to build the app
```
/path/to/my/android_app/app/build/generated/source/kapt/debug/com/my_app/android/databinding/FragmentLoginBindingImpl.java:215: error: cannot access User
    private boolean onChangeViewModelUser(androidx.lifecycle.MutableLiveData<com.my_app.android.database.models.User> ViewModelUser, int fieldId) {
                                                                                                              ^
  bad class file: /path/to/my/android_app/app/build/tmp/kotlin-classes/debug/com/my_app/android/database/models/User.class
    undeclared type variable: T
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

Any insight on this would be appreciated, Thanks!

**Comment by nhachicha** [comment]
Hi @robbieadi inside `LoginViewModel` how are you emitting the value of `User`? are they already persisted in Realm or are they unmanaged. Could you please share this part of the logic?

**Comment by robbieadi** [comment]
> Hi @robbieadi inside `LoginViewModel` how are you emitting the value of `User`? are they already persisted in Realm or are they unmanaged. Could you please share this part of the logic?

I query the user as flow and convert it to live data with `androidx.lifecycle.asLiveData` so it's pretty much like this.
```
realm.query<User>().first().asFlow().map { it.obj }.asLiveData()
```

I don't think it matters how the object is queried. If you have live data of realm object and use data binding to do things in your layout, you will get an error when android studio tries to generate the binding class.

**Comment by robbieadi** [comment]
> @robbieadi I created a sample based on the official `KotlinCoroutineswithArchitectureComponentsLiveDataViewModelLifecycle` with Realm, it works as expected. Could you please have a look and see if this matches your use case, or find a way to make it crash so we can have a repro to investigate
> 
> Cheers [KotlinCoroutineswithArchitectureComponentsLiveDataViewModelLifecycle.zip](https://github.com/realm/realm-kotlin/files/9101932/KotlinCoroutineswithArchitectureComponentsLiveDataViewModelLifecycle.zip)

Ah, I see. I was using version `1.0.0`, but once I updated it to `1.0.1` I can now build the app successfully.
As for reproducing the error you can easily reproduce it by downgrading the realm to version `1.0.0` in your `KotlinCoroutineswithArchitectureComponentsLiveDataViewModelLifecycle` app.

Thanks for your help @nhachicha!

**Comment by rorbech** [comment]
Duplicate of #901
