### ISSUE TITLE
How to use ".assetFile" property in Realm-Kotlin SDK ?

### ISSUE THREAD

**Issue by abdulkadirgun** [realm/realm-kotlin#927]
In Java SDK, I was creating Realm.Configuration object with the realm file that located in asset folder. I couldn't find any equivalent property in Realm Kotlin SDK

in java SDK:

```
val populatedRealmConfiguration = RealmConfiguration.Builder()
    .schemaVersion(REALM_VERSION)
    .compactOnLaunch()
    .encryptionKey(resolveEncrypt(RealmHelperStatics.EncRealmKey).toByteArray())
    .assetFile("populated.realm")
    .name("populated.realm")
    .allowQueriesOnUiThread(true)
    .allowWritesOnUiThread(true)
    .build()
```

[I have followed the java to kotlin migration guide ](https://www.mongodb.com/docs/realm/sdk/kotlin/migrate-from-java-sdk-to-kotlin-sdk/). but I found nothing.
How to use ".assetFile" property in Kotlin SDK ?

**Comment by edualonso** [comment]
Hi @abdulkadirgun. The `assetFile` feature isn't available in the Kotlin SDK yet. Please refer to https://github.com/realm/realm-kotlin/issues/577 to track its progress.
