### ISSUE TITLE
Flexible sync of RealmObject with EmbeddedRealmObject field

### ISSUE THREAD

**Issue by klamborowski** [realm/realm-kotlin#945]
Hi :wave: 

I'm trying to use kotlin realm sdk for Flexible Sync. 

For standard Realm object like this it's work perfect:

```
open class SomeClass(
    @PrimaryKey var _id: String = "",
    var _partition: String = "",
    var card: String? = null,
) : RealmObject 
```

But for embedded object 
```
open class SomeClass(
    @PrimaryKey var _id: String = "",
    var _partition: String = "",
    var card: Card? = null,
) : RealmObject 

open class Card(
    var cardNumber: String? = null,
    var isPrivateCard: Boolean? = null,
    var uuid: String? = null
) : EmbeddedRealmObject
```

I can't pass Card:class to SyncConfiguration like bellow, cause schema argument only takes set of RealmObject, not BaseRealmObject.
```
SyncConfiguration.Builder(
        user = getCurrentUser(),
        schema = setOf(SomeClass::class, Card::class)
    )
```

But if I add only SomeClass:class
```
SyncConfiguration.Builder(
        user = getCurrentUser(),
        schema = setOf(SomeClass::class)
    )
```
I will receive the following error and app crash:

```
     Caused by: io.realm.kotlin.internal.interop.RealmCoreLogicException: [18]: Schema validation failed due to the following errors:
2022-07-29 17:07:53.490 11177-11177/my.app.dev E/AndroidRuntime: - Property 'SomeClass.card' of type 'object' has unknown object type 'Card'
```

Looking forward for your help :)

**Comment by cmelchior** [comment]
Hi @klamborowski Thank you for reporting this. This is an unfortunate bug in our SyncConfiguration that wasn't caught for some reason. We should have a patch ready in a day or two. Sorry for the inconvenience.

**Comment by cmelchior** [comment]
A fix should be ready in `1.0.2-SNAPSHOT`. We will make a proper release shortly.

**Comment by klamborowski** [comment]
Great news! Thanks for a quick fix 😊

**Comment by cmelchior** [comment]
A proper 1.0.2 release is now out.
