### ISSUE TITLE
Kotlin data class support

### ISSUE THREAD

**Issue by Burtan** [realm/realm-kotlin#946]
Hi,
are there any plans to support data classes? Not being able to have immutable fields on RealmObjects is a big restrictions!
Thanks!

**Comment by cmelchior** [comment]
Hi @Burtan 

We are probably not going to support model classes as data classes as the data in Realm is inherently mutable, but we have talked about support _projections_, which represent a read-only view of the data. In that case, exposing it as immutable data classes would be natural. You can read more here: https://github.com/realm/realm-kotlin/issues/947

**Comment by cmelchior** [comment]
Closing as duplicate of #947
