### ISSUE TITLE
Support for deleting Realms

### ISSUE THREAD

**Issue by rorbech** [realm/realm-kotlin#95]
We need to be able to delete the actual files of a Realm. 

As of now the is no C-API for ensuring exclusive access to the files like the old 
```
DB::call_with_lock(realm_path, [&](std::string path)
```
from Java.

**Comment by cmelchior** [comment]
Added https://github.com/realm/realm-core/issues/5058

**Comment by fealebenpae** [comment]
Please see https://github.com/realm/realm-core/pull/5127.
