### ISSUE TITLE
Alternative to writeEncryptedCopyTo from realm-java

### ISSUE THREAD

**Issue by ganfra** [realm/realm-kotlin#952]
We are migrating our code from realm-java to realm-kotlin. 
We were using `writeEncryptedCopyTo` method, but it doesn't exist on realm-kotlin.
Is there anyway to do the same thing?

**Comment by cmelchior** [comment]
Hi @ganfra There is currently no method like that available. You would need to copy the file manually currently. We are in the process of adding it though and it should hopefully land within the next few days: #955 

Folding this into #570
