### ISSUE TITLE
Calling sort().first().find() doesn't work

### ISSUE THREAD

**Issue by ganfra** [realm/realm-kotlin#953]
Want to sort a list and retrieve the first one with `sort().first().find()` but it doesn't work.
Using `sort().find().firstOrNull()` will work instead.

**Comment by cmelchior** [comment]
@ganfra When you say it doesn't work, what do you mean exactly? Can you share an example?

**Comment by ganfra** [comment]
Yes sorry, I was not clear.
So the result is not returned sorted as I'd have expected.
But if I just call `find().firstOrNull()`instead it respects the sort operator.

Exemple: 

```
class Task : RealmObject {
    @PrimaryKey
    var id: Long = 0,
    var name: String = ""
    var lastEditTs: Long = 0
}
```

If I want to get the latest edited task: 
`realm.query(Task::class).sort("lastEditTs", Sort.DESCENDING).first().find() `=> will return the first edited 
`realm.query(Task::class).sort("lastEditTs", Sort.DESCENDING).find().firstOrNull()` => will return the last edited

**Comment by clementetb** [comment]
@ganfra Thanks for the clarification, we were able to reproduce the issue.
