### ISSUE TITLE
Opening a realm with `initialSubscriptions` while offline blocks its initialisation

### ISSUE THREAD

**Issue by edualonso** [realm/realm-kotlin#961]
Opening a realm after having specified `initialSubscriptions` in the sync config while offline causes the initialisation to hang. We should be able to open a flexible sync enabled realm with subscriptions even if the device has no connectivity.

**Comment by rorbech** [comment]
Java equivalent for some insight: https://github.com/realm/realm-java/issues/7712

**Comment by rorbech** [comment]
Seems like this is already covered by the logic in https://github.com/realm/realm-kotlin/blob/main/packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncConfigurationImpl.kt#L132..L141. This only waits for the initial data if specifically requested with `SyncConfiguration.Builder.waitForInitialRemoteData` which I guess should be OK.

**Comment by rorbech** [comment]
I can't really figure out a way to test this automatically, but I have verified it manually on Android with the below test and manually shutting down the server during the delay. 

```
    @Test
    fun initialSubscriptions_notBlockingWhenOffline(): Unit = runBlocking {
        println("Shutdown server manually")
        delay(30000)
        val config = SyncConfiguration.Builder(app.currentUser!!, defaultSchema)
            .initialSubscriptions { realm ->
                repeat(10) {
                    add(realm.query<FlexParentObject>("section = $0", it))
                }
            }
            .build()
        Realm.open(config).use {
        }
        println("DONE")
    }
```
Adding a `.waitForInitialRemoteData(10.seconds)` will cause a timeout exception and not open the realm, so it seems like the logic is in place.
