### ISSUE TITLE
Realm 1.0.2 missing for iosarm64

### ISSUE THREAD

**Issue by tarasmorskyi-mediamonks** [realm/realm-kotlin#968]
After updating to 1.0.2 receiving this error. It doesn't block Android build, but AS is complaining about module with this dependency and doesn't index it correctly
```
Failed building KotlinMPPGradleModel
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find cinterop.klib (io.realm.kotlin:cinterop-iosarm64:1.0.2).
Searched in the following locations:
    https://plugins.gradle.org/m2/io/realm/kotlin/cinterop-iosarm64/1.0.2/cinterop-iosarm64-1.0.2.klib

```

**Comment by cmelchior** [comment]
Hmm, that looks a bit weird. It should be present here at least https://search.maven.org/search?q=a:cinterop-iosarm64

Not 100% sure why it is only searching the Gradle Plugin Portal 🤔
