### ISSUE TITLE
what is the best practise to handle Realm instance

### ISSUE THREAD

**Issue by ohyooo** [realm/realm-kotlin#975]
I got this error when I try to insert thousands of items into db. it crashed after 100+ items were inserted.

```kotlin
val realm = Realm.open(conf)
realm.write {
  list.forEach(::copyToRealm)
}

or

list.forEach {
    realm.write { copyToRealm(it) }
}
```

```log
java.lang.IllegalArgumentException: Could not execute the write transaction: RealmCoreException([2]: mmap() failed: Out of memory size: 48971776 offset: 0)
```

I try to write a cahce to fix this. a map with db name and call count, Realm instance will be closed after 10 write transcation then create a new one.
it now can finish 1400+ insert but still got OOM crash then, and it's crashed at Realm.open(), not in write transcation.

it's ok with realm-java. I don't know what i missed in document.

**Comment by cmelchior** [comment]
Hi ohyoo. Each `write` is actually a database transaction, which is a pretty heavy thing, and not something that is intended to be called in a tight loop. We should probably clarify the docs around this method. The correct way is to do this:

```
val realm = Realm.open(conf) // Should be done once in the app

// Iterate inside the `write`
realm.write {
  list.forEach(::copyToRealm)
}
```

Doing it like that shouldn't cause OOM issues.

**Comment by ohyooo** [comment]
thanks for replying. I will think how to handle my logic in this way :)
