### ISSUE TITLE
how to convert model to json?

### ISSUE THREAD

**Issue by zihadrizkyef** [realm/realm-kotlin#983]
Sometimes we need to convert the model instance to json. E.g. to write the instance to sharepref.
So, how can we convert the model instance to json? Due to there's no copyFromRealm() in realm-kotlin, using Gson().toJson(model) is giving java.lang.StackOverflowError: stack size 8192KB

**Comment by ohyooo** [comment]
https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/serialization/

**Comment by cmelchior** [comment]
Hi @zihadrizkyef Have you looked into Kotlin Serialization which should support this? https://kotlinlang.org/docs/serialization.html

Currently, we have issues with GSON due to the reason you mention, we are tracking `copyFromRealm` here: #549

**Comment by cmelchior** [comment]
Hi @zihadrizkyef As @ohyooo mentions, you need special support for GSON due to how it handles some of our internal fields.

**Comment by cmelchior** [comment]
Hi @zihadrizkyef. I assume the above answers your question, so closing this issue. Feel free to reopen if it still doesn't work.

**Comment by zihadrizkyef** [comment]
> https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/serialization/

Thank you, It helps me a lot. But still error if there's realm list inside the model

> Process: com.olserapratama.pos3, PID: 17541
    java.lang.IllegalArgumentException: field com.olserapratama.repository.repository.local.model.salesorder.SalesOrder.creditPayments has type io.realm.kotlin.types.RealmList, got java.util.ArrayList
        at java.lang.reflect.Field.set(Native Method)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:166)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:266)
        at com.google.gson.Gson.fromJson(Gson.java:1058)
        at com.google.gson.Gson.fromJson(Gson.java:1016)
        at com.google.gson.Gson.fromJson(Gson.java:959)

Is there solution for this error?
