### ISSUE TITLE
Realm SharedFlow, StateFlow not updating.

### ISSUE THREAD

**Issue by benedictcontawe** [realm/realm-kotlin#988]
Using Shared Flow and State Flow not updating, But Inserting Deleting and Deleting All are Responsive.
upon updating the names its not emitting 

Code Link: https://github.com/benedictcontawe/JetpackComponentsApp/tree/Kotlin_Realm_Coroutines_Flow

**Comment by edualonso** [comment]
Hi @benedictcontawe. I've checked out your code and looks fine. I receive updates in the call to `viewModel.observeItems().collect(...)` located in MainFragment line 66 whenever I add/update/delete an item.

I can see you just committed some changes as recently as an hour ago. Did those changes by any chance fixed your problem?

**Comment by benedictcontawe** [comment]
yes instead of using StateFlow I use Shared flow

**Comment by edualonso** [comment]
OK, I was playing around making some updates with your app and whether they get emitted when using a `StateFlow` just out of curiosity and I can confirm they are emitted correctly by Realm. I modified the `MainViewModel.observeItems()` function to return a `StateFlow`:
```
suspend fun observeItems() : StateFlow<List<CustomModel>> {
        return ConvertList.toStateFlowListModel(customRepository.getAllFlow() ?: emptyFlow<ResultsChange<CustomObject>>(), viewModelScope)
    }
```
and added the following to `CustomRepository.getAllFlow()`:
```
override public suspend fun getAllFlow() : Flow<ResultsChange<CustomObject>>? {
        return realm?.query<CustomObject>()?.find()?.asFlow()
            ?.map {
                Log.d("---", "${it.list[0].name}")
                it
            }
    }
```
The updated name is dumped correctly on the Logcat window so it appears there is problem in how you configured your `StateFlow`. I will close the issue, let us know if you have more questions.

**Comment by benedictcontawe** [comment]
yeah thanks
