### ISSUE TITLE
Support Realm Functions & Custom Auth

### ISSUE THREAD

**Issue by bainfu** [realm/realm-kotlin#997]
The Kotlin SDK looks so promising, especially with the segmentation of code. However it omits one feature such as the usage of Realm Functions, which I assume is why Custom Auth is absent as well.  Is this on the roadmap?

**Comment by cmelchior** [comment]
Hi @bainfu 

Yes, all of these features depend on a Multiplatform aware BSON library. We have already started on the implementation and hope to have something to share soon. You can follow this issue for progress on it https://github.com/realm/realm-kotlin/issues/648
